[package]
authors = ["Devon Govett <devongovett@gmail.com>"]
name = "parcel-css"
version = "0.1.0"
edition = "2024"

[dependencies]
parcel-core = { path = "../core" }
lightningcss = { git = "https://github.com/parcel-bundler/lightningcss.git", features = ["into_owned", "visitor"] }
serde = { version = "1.0.228", features = ["derive", "rc"] }
parcel_sourcemap = "*"
