import { Person } from "original";
Person.prototype.greet = function() { return `Hello ${this.name}!` }

// This will be present in the .d.ts file generated by parcel:
export const anotherThing: string = "hello";

// This will get dropped:
declare module "original" {
  interface Person {
    greet(): string;
  }
}

// This will also get dropped, if the "declare module" statement above is present:
export const somethingElse: string = "goodbye";