[workspace]
resolver = "2"
members = [
  "crates/*",
  "packages/transformers/js/core"
]

[profile.canary]
inherits = "release"
debug = true

[profile.release]
lto = true
codegen-units = 1
panic = 'abort'
strip = true

[patch.crates-io]
html5ever = { git = "https://github.com/devongovett/html5ever.git", branch = "xmlns-attrs" }
xml5ever = { git = "https://github.com/devongovett/html5ever.git", branch = "xmlns-attrs" }
markup5ever = { git = "https://github.com/devongovett/html5ever.git", branch = "xmlns-attrs" }
