#include <stdio.h>
#include "libjavaplugin.h" // Generated by GraalVM

__attribute__((visibility("default")))
extern int parcel_plugin_transform(long long asset) {
  graal_isolate_t *isolate = NULL;
  graal_isolatethread_t *thread = NULL;

  // 1. Initialize the GraalVM runtime (Isolate)
  if (graal_create_isolate(NULL, &isolate, &thread) != 0) {
      fprintf(stderr, "Initialization failed\n");
      return 1;
  }

  // 2. Call your Java method directly!
  printf("CALLING JAVA %lld\n", asset);
  parcel_transform(thread, asset);

  // 3. Clean up
  graal_tear_down_isolate(thread);
  return 0;
}
