[package]
authors = ["Devon Govett <devongovett@gmail.com>"]
name = "parcel-js"
version = "0.1.0"
edition = "2024"

[dependencies]
parcel-core = { path = "../core" }
serde = { version = "1.0.228", features = ["derive", "rc"] }
serde_json = { version = "1.0.149", features = ["preserve_order", "raw_value"] }
parcel-js-swc-core = { path = "../../packages/transformers/js/core" }
indexmap = { version = "2.11.0", features = ["serde"] }
parcel-plugin-js = { path = "../plugin-js" }
parcel-css = { path = "../css" }
parcel-resolver = { path = "../parcel-resolver" }
parcel-macros = { path = "../macros" }
node-semver = "2.2.0"
glob-match = "*"
swc_core = { version = "77", features = ["ecma_ast", "ecma_quote"] }
fixedbitset = "0.5.7"
bytecount = "0.6.9"
simd-utf16-len = "0.1.0"

[build-dependencies]
swc_core = { version = "77", features = [
  "common",
  "ecma_ast",
  "ecma_codegen",
  "ecma_minifier",
  "ecma_parser",
  "ecma_transforms",
  "ecma_visit",
] }
