// flow-typed signature: 27e995e11a57ab7a1e817bab4b4a5c57
// flow-typed version: <<STUB>>/vscode-jsonrpc_v6.0.0/flow_v0.146.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'vscode-jsonrpc'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'vscode-jsonrpc' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'vscode-jsonrpc/browser' {
  declare module.exports: any;
}

declare module 'vscode-jsonrpc/lib/browser/main' {
  declare module.exports: any;
}

declare module 'vscode-jsonrpc/lib/browser/ril' {
  declare module.exports: any;
}

declare module 'vscode-jsonrpc/lib/common/api' {
  declare module.exports: any;
}

declare module 'vscode-jsonrpc/lib/common/cancellation' {
  declare module.exports: any;
}

declare module 'vscode-jsonrpc/lib/common/connection' {
  declare module.exports: any;
}

declare module 'vscode-jsonrpc/lib/common/disposable' {
  declare module.exports: any;
}

declare module 'vscode-jsonrpc/lib/common/encoding' {
  declare module.exports: any;
}

declare module 'vscode-jsonrpc/lib/common/events' {
  declare module.exports: any;
}

declare module 'vscode-jsonrpc/lib/common/is' {
  declare module.exports: any;
}

declare module 'vscode-jsonrpc/lib/common/linkedMap' {
  declare module.exports: any;
}

declare module 'vscode-jsonrpc/lib/common/messageBuffer' {
  declare module.exports: any;
}

declare module 'vscode-jsonrpc/lib/common/messageReader' {
  declare module.exports: any;
}

declare module 'vscode-jsonrpc/lib/common/messages' {
  declare module.exports: any;
}

declare module 'vscode-jsonrpc/lib/common/messageWriter' {
  declare module.exports: any;
}

declare module 'vscode-jsonrpc/lib/common/ral' {
  declare module.exports: any;
}

declare module 'vscode-jsonrpc/lib/common/semaphore' {
  declare module.exports: any;
}

declare module 'vscode-jsonrpc/lib/node/main' {
  declare module.exports: any;
}

declare module 'vscode-jsonrpc/lib/node/ril' {
  declare module.exports: any;
}

declare module 'vscode-jsonrpc/node' {
  declare module.exports: any;
}

// Filename aliases
declare module 'vscode-jsonrpc/browser.js' {
  declare module.exports: $Exports<'vscode-jsonrpc/browser'>;
}
declare module 'vscode-jsonrpc/lib/browser/main.js' {
  declare module.exports: $Exports<'vscode-jsonrpc/lib/browser/main'>;
}
declare module 'vscode-jsonrpc/lib/browser/ril.js' {
  declare module.exports: $Exports<'vscode-jsonrpc/lib/browser/ril'>;
}
declare module 'vscode-jsonrpc/lib/common/api.js' {
  declare module.exports: $Exports<'vscode-jsonrpc/lib/common/api'>;
}
declare module 'vscode-jsonrpc/lib/common/cancellation.js' {
  declare module.exports: $Exports<'vscode-jsonrpc/lib/common/cancellation'>;
}
declare module 'vscode-jsonrpc/lib/common/connection.js' {
  declare module.exports: $Exports<'vscode-jsonrpc/lib/common/connection'>;
}
declare module 'vscode-jsonrpc/lib/common/disposable.js' {
  declare module.exports: $Exports<'vscode-jsonrpc/lib/common/disposable'>;
}
declare module 'vscode-jsonrpc/lib/common/encoding.js' {
  declare module.exports: $Exports<'vscode-jsonrpc/lib/common/encoding'>;
}
declare module 'vscode-jsonrpc/lib/common/events.js' {
  declare module.exports: $Exports<'vscode-jsonrpc/lib/common/events'>;
}
declare module 'vscode-jsonrpc/lib/common/is.js' {
  declare module.exports: $Exports<'vscode-jsonrpc/lib/common/is'>;
}
declare module 'vscode-jsonrpc/lib/common/linkedMap.js' {
  declare module.exports: $Exports<'vscode-jsonrpc/lib/common/linkedMap'>;
}
declare module 'vscode-jsonrpc/lib/common/messageBuffer.js' {
  declare module.exports: $Exports<'vscode-jsonrpc/lib/common/messageBuffer'>;
}
declare module 'vscode-jsonrpc/lib/common/messageReader.js' {
  declare module.exports: $Exports<'vscode-jsonrpc/lib/common/messageReader'>;
}
declare module 'vscode-jsonrpc/lib/common/messages.js' {
  declare module.exports: $Exports<'vscode-jsonrpc/lib/common/messages'>;
}
declare module 'vscode-jsonrpc/lib/common/messageWriter.js' {
  declare module.exports: $Exports<'vscode-jsonrpc/lib/common/messageWriter'>;
}
declare module 'vscode-jsonrpc/lib/common/ral.js' {
  declare module.exports: $Exports<'vscode-jsonrpc/lib/common/ral'>;
}
declare module 'vscode-jsonrpc/lib/common/semaphore.js' {
  declare module.exports: $Exports<'vscode-jsonrpc/lib/common/semaphore'>;
}
declare module 'vscode-jsonrpc/lib/node/main.js' {
  declare module.exports: $Exports<'vscode-jsonrpc/lib/node/main'>;
}
declare module 'vscode-jsonrpc/lib/node/ril.js' {
  declare module.exports: $Exports<'vscode-jsonrpc/lib/node/ril'>;
}
declare module 'vscode-jsonrpc/node.js' {
  declare module.exports: $Exports<'vscode-jsonrpc/node'>;
}
