// flow-typed signature: a099272ddf8e8304ae56901c08505e04
// flow-typed version: <<STUB>>/vscode-languageserver_v7.0.0/flow_v0.146.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'vscode-languageserver'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'vscode-languageserver' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'vscode-languageserver/browser' {
  declare module.exports: any;
}

declare module 'vscode-languageserver/lib/browser/main' {
  declare module.exports: any;
}

declare module 'vscode-languageserver/lib/common/api' {
  declare module.exports: any;
}

declare module 'vscode-languageserver/lib/common/callHierarchy' {
  declare module.exports: any;
}

declare module 'vscode-languageserver/lib/common/configuration' {
  declare module.exports: any;
}

declare module 'vscode-languageserver/lib/common/fileOperations' {
  declare module.exports: any;
}

declare module 'vscode-languageserver/lib/common/linkedEditingRange' {
  declare module.exports: any;
}

declare module 'vscode-languageserver/lib/common/moniker' {
  declare module.exports: any;
}

declare module 'vscode-languageserver/lib/common/progress' {
  declare module.exports: any;
}

declare module 'vscode-languageserver/lib/common/semanticTokens' {
  declare module.exports: any;
}

declare module 'vscode-languageserver/lib/common/server' {
  declare module.exports: any;
}

declare module 'vscode-languageserver/lib/common/showDocument' {
  declare module.exports: any;
}

declare module 'vscode-languageserver/lib/common/utils/is' {
  declare module.exports: any;
}

declare module 'vscode-languageserver/lib/common/utils/uuid' {
  declare module.exports: any;
}

declare module 'vscode-languageserver/lib/common/workspaceFolders' {
  declare module.exports: any;
}

declare module 'vscode-languageserver/lib/node/files' {
  declare module.exports: any;
}

declare module 'vscode-languageserver/lib/node/main' {
  declare module.exports: any;
}

declare module 'vscode-languageserver/lib/node/resolve' {
  declare module.exports: any;
}

declare module 'vscode-languageserver/node' {
  declare module.exports: any;
}

// Filename aliases
declare module 'vscode-languageserver/browser.js' {
  declare module.exports: $Exports<'vscode-languageserver/browser'>;
}
declare module 'vscode-languageserver/lib/browser/main.js' {
  declare module.exports: $Exports<'vscode-languageserver/lib/browser/main'>;
}
declare module 'vscode-languageserver/lib/common/api.js' {
  declare module.exports: $Exports<'vscode-languageserver/lib/common/api'>;
}
declare module 'vscode-languageserver/lib/common/callHierarchy.js' {
  declare module.exports: $Exports<'vscode-languageserver/lib/common/callHierarchy'>;
}
declare module 'vscode-languageserver/lib/common/configuration.js' {
  declare module.exports: $Exports<'vscode-languageserver/lib/common/configuration'>;
}
declare module 'vscode-languageserver/lib/common/fileOperations.js' {
  declare module.exports: $Exports<'vscode-languageserver/lib/common/fileOperations'>;
}
declare module 'vscode-languageserver/lib/common/linkedEditingRange.js' {
  declare module.exports: $Exports<'vscode-languageserver/lib/common/linkedEditingRange'>;
}
declare module 'vscode-languageserver/lib/common/moniker.js' {
  declare module.exports: $Exports<'vscode-languageserver/lib/common/moniker'>;
}
declare module 'vscode-languageserver/lib/common/progress.js' {
  declare module.exports: $Exports<'vscode-languageserver/lib/common/progress'>;
}
declare module 'vscode-languageserver/lib/common/semanticTokens.js' {
  declare module.exports: $Exports<'vscode-languageserver/lib/common/semanticTokens'>;
}
declare module 'vscode-languageserver/lib/common/server.js' {
  declare module.exports: $Exports<'vscode-languageserver/lib/common/server'>;
}
declare module 'vscode-languageserver/lib/common/showDocument.js' {
  declare module.exports: $Exports<'vscode-languageserver/lib/common/showDocument'>;
}
declare module 'vscode-languageserver/lib/common/utils/is.js' {
  declare module.exports: $Exports<'vscode-languageserver/lib/common/utils/is'>;
}
declare module 'vscode-languageserver/lib/common/utils/uuid.js' {
  declare module.exports: $Exports<'vscode-languageserver/lib/common/utils/uuid'>;
}
declare module 'vscode-languageserver/lib/common/workspaceFolders.js' {
  declare module.exports: $Exports<'vscode-languageserver/lib/common/workspaceFolders'>;
}
declare module 'vscode-languageserver/lib/node/files.js' {
  declare module.exports: $Exports<'vscode-languageserver/lib/node/files'>;
}
declare module 'vscode-languageserver/lib/node/main.js' {
  declare module.exports: $Exports<'vscode-languageserver/lib/node/main'>;
}
declare module 'vscode-languageserver/lib/node/resolve.js' {
  declare module.exports: $Exports<'vscode-languageserver/lib/node/resolve'>;
}
declare module 'vscode-languageserver/node.js' {
  declare module.exports: $Exports<'vscode-languageserver/node'>;
}
