[package]
authors = ["Devon Govett <devongovett@gmail.com>"]
name = "parcel-resolver"
version = "0.1.1"
license = "MIT"
repository = "https://github.com/parcel-bundler/parcel"
keywords = ["resolver", "node", "cjs", "esm", "bundler"]
description = "Node.js compatible module resolver used by the Parcel bundler"
edition = "2024"

[dependencies]
bitflags = { version = "2.7.0", features = ["serde"] }
papaya = "0.2.4"
glob-match = "0.2.1"
indexmap = { version = "1.9.2", features = ["serde"] }
itertools = "0.10.5"
parking_lot = "0.12"
percent-encoding = "2.2.0"
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.91"
url = "2.5.4"
rustc-hash = "2.0.0"
parcel-core = { path = "../core" }

[dev-dependencies]
assert_fs = "1.1.4"
criterion = { version = "*", features = ["html_reports"] }

[target.'cfg(windows)'.dev-dependencies]
is_elevated = "0.1.2"


[[bench]]
name = "benchmark"
harness = false
