/* automatically generated by rust-bindgen 0.72.1 */

pub const PARCEL_ABI_VERSION: u32 = 1;
pub const PARCEL_INVALID_ASSET_INDEX: u32 = 4294967295;
#[repr(u8)]
#[derive(Debug, Copy, Clone, Hash, PartialEq, Eq)]
pub enum DiagnosticSeverity {
  Error = 0,
  Warning = 1,
  SourceError = 2,
  Info = 3,
}
#[repr(u8)]
#[derive(Debug, Copy, Clone, Hash, PartialEq, Eq)]
pub enum BundleBehavior {
  None = 0,
  Inline = 1,
  Isolated = 2,
}
#[repr(u8)]
#[derive(Debug, Copy, Clone, Hash, PartialEq, Eq)]
pub enum BundleGraphResolutionType {
  Invalid = 0,
  None = 1,
  Deferred = 2,
  External = 3,
  Excluded = 4,
  Asset = 5,
  Bundle = 6,
}
#[repr(u8)]
#[derive(Debug, Copy, Clone, Hash, PartialEq, Eq)]
pub enum SpecifierType {
  Esm = 0,
  Commonjs = 1,
  Url = 2,
  Custom = 3,
}
#[repr(u8)]
#[derive(Debug, Copy, Clone, Hash, PartialEq, Eq)]
pub enum Priority {
  Sync = 0,
  Parallel = 1,
  Lazy = 2,
}
#[repr(u8)]
#[derive(Debug, Copy, Clone, Hash, PartialEq, Eq)]
pub enum Environment {
  Browser = 0,
  WebWorker = 1,
  ServiceWorker = 2,
  Worklet = 3,
  Node = 4,
  ElectronMain = 5,
  ElectronRenderer = 6,
  ReactClient = 7,
  ReactServer = 8,
}
#[repr(u8)]
#[derive(Debug, Copy, Clone, Hash, PartialEq, Eq)]
pub enum OutputFormat {
  Global = 0,
  Commonjs = 1,
  Esmodule = 2,
}
#[repr(u8)]
#[derive(Debug, Copy, Clone, Hash, PartialEq, Eq)]
pub enum SourceType {
  Module = 0,
  Script = 1,
}
#[repr(u8)]
#[doc = " The level of a log event, and of a message passed to `parcel_options_log()`."]
#[derive(Debug, Copy, Clone, Hash, PartialEq, Eq)]
pub enum LogLevel {
  None = 0,
  Error = 1,
  Warn = 2,
  Info = 3,
  Verbose = 4,
}
#[repr(u8)]
#[doc = " Result of a plugin's `parcel_plugin_init()`.\n\n A plugin that cannot use the [`ParcelApi`](crate::ParcelApi) table it was\n handed returns `PARCEL_INIT_INCOMPATIBLE` without writing a diagnostic — it\n has no way to allocate one, since allocating goes through the very table it\n just rejected. Parcel writes that diagnostic instead."]
#[derive(Debug, Copy, Clone, Hash, PartialEq, Eq)]
pub enum InitStatus {
  #[doc = " The plugin initialized. Its state, if any, is in the `state` out param."]
  Ok = 0,
  #[doc = " The plugin failed and wrote a diagnostic describing why."]
  Error = 1,
  #[doc = " The plugin cannot run against this build of Parcel. No diagnostic was\n written; Parcel reports the mismatch."]
  Incompatible = 2,
}
#[repr(u8)]
#[derive(Debug, Copy, Clone, Hash, PartialEq, Eq)]
pub enum ResolutionType {
  None = 0,
  FilePath = 1,
  External = 2,
  Excluded = 3,
}
#[repr(u8)]
#[doc = " The kind of event passed to `parcel_plugin_report()`."]
#[derive(Debug, Copy, Clone, Hash, PartialEq, Eq)]
pub enum ReportEventType {
  BuildStart = 0,
  BuildSuccess = 1,
  BuildFailure = 2,
  Log = 3,
}
impl DependencyFlags {
  pub const ENTRY: DependencyFlags = DependencyFlags(1);
  pub const OPTIONAL: DependencyFlags = DependencyFlags(2);
  pub const NEEDS_STABLE_NAME: DependencyFlags = DependencyFlags(4);
  pub const IS_WEBWORKER: DependencyFlags = DependencyFlags(8);
  pub const SIDE_EFFECTS: DependencyFlags = DependencyFlags(16);
  pub const MACRO: DependencyFlags = DependencyFlags(32);
}
impl ::std::ops::BitOr<DependencyFlags> for DependencyFlags {
  type Output = Self;
  #[inline]
  fn bitor(self, other: Self) -> Self {
    DependencyFlags(self.0 | other.0)
  }
}
impl ::std::ops::BitOrAssign for DependencyFlags {
  #[inline]
  fn bitor_assign(&mut self, rhs: DependencyFlags) {
    self.0 |= rhs.0;
  }
}
impl ::std::ops::BitAnd<DependencyFlags> for DependencyFlags {
  type Output = Self;
  #[inline]
  fn bitand(self, other: Self) -> Self {
    DependencyFlags(self.0 & other.0)
  }
}
impl ::std::ops::BitAndAssign for DependencyFlags {
  #[inline]
  fn bitand_assign(&mut self, rhs: DependencyFlags) {
    self.0 &= rhs.0;
  }
}
#[repr(transparent)]
#[derive(Debug, Copy, Clone, Hash, PartialEq, Eq)]
pub struct DependencyFlags(pub u8);
impl ExportsConditions {
  pub const IMPORT: ExportsConditions = ExportsConditions(1);
  pub const REQUIRE: ExportsConditions = ExportsConditions(2);
  pub const MODULE: ExportsConditions = ExportsConditions(4);
  pub const NODE: ExportsConditions = ExportsConditions(8);
  pub const BROWSER: ExportsConditions = ExportsConditions(16);
  pub const WORKER: ExportsConditions = ExportsConditions(32);
  pub const WORKLET: ExportsConditions = ExportsConditions(64);
  pub const ELECTRON: ExportsConditions = ExportsConditions(128);
  pub const DEVELOPMENT: ExportsConditions = ExportsConditions(256);
  pub const PRODUCTION: ExportsConditions = ExportsConditions(512);
  pub const TYPES: ExportsConditions = ExportsConditions(1024);
  pub const DEFAULT: ExportsConditions = ExportsConditions(2048);
  pub const STYLE: ExportsConditions = ExportsConditions(4096);
  pub const SASS: ExportsConditions = ExportsConditions(8192);
  pub const LESS: ExportsConditions = ExportsConditions(16384);
  pub const STYLUS: ExportsConditions = ExportsConditions(32768);
  pub const REACT_SERVER: ExportsConditions = ExportsConditions(65536);
  pub const SOURCE: ExportsConditions = ExportsConditions(131072);
}
impl ::std::ops::BitOr<ExportsConditions> for ExportsConditions {
  type Output = Self;
  #[inline]
  fn bitor(self, other: Self) -> Self {
    ExportsConditions(self.0 | other.0)
  }
}
impl ::std::ops::BitOrAssign for ExportsConditions {
  #[inline]
  fn bitor_assign(&mut self, rhs: ExportsConditions) {
    self.0 |= rhs.0;
  }
}
impl ::std::ops::BitAnd<ExportsConditions> for ExportsConditions {
  type Output = Self;
  #[inline]
  fn bitand(self, other: Self) -> Self {
    ExportsConditions(self.0 & other.0)
  }
}
impl ::std::ops::BitAndAssign for ExportsConditions {
  #[inline]
  fn bitand_assign(&mut self, rhs: ExportsConditions) {
    self.0 &= rhs.0;
  }
}
#[repr(transparent)]
#[doc = " Conditions used when resolving package `exports` and `imports` fields."]
#[derive(Debug, Copy, Clone, Hash, PartialEq, Eq)]
pub struct ExportsConditions(pub u32);
impl AssetFlags {
  pub const IS_SOURCE: AssetFlags = AssetFlags(1);
  pub const SIDE_EFFECTS: AssetFlags = AssetFlags(2);
  pub const IS_BUNDLE_SPLITTABLE: AssetFlags = AssetFlags(4);
  pub const LARGE_BLOB: AssetFlags = AssetFlags(8);
  pub const HAS_CJS_EXPORTS: AssetFlags = AssetFlags(16);
  pub const STATIC_EXPORTS: AssetFlags = AssetFlags(32);
  pub const SHOULD_WRAP: AssetFlags = AssetFlags(64);
  pub const IS_CONSTANT_MODULE: AssetFlags = AssetFlags(128);
  pub const HAS_NODE_REPLACEMENTS: AssetFlags = AssetFlags(256);
  pub const HAS_SYMBOLS: AssetFlags = AssetFlags(512);
  pub const IS_HTML_ATTR: AssetFlags = AssetFlags(1024);
  pub const IS_HTML_TAG: AssetFlags = AssetFlags(2048);
  pub const IS_ESM: AssetFlags = AssetFlags(4096);
}
impl ::std::ops::BitOr<AssetFlags> for AssetFlags {
  type Output = Self;
  #[inline]
  fn bitor(self, other: Self) -> Self {
    AssetFlags(self.0 | other.0)
  }
}
impl ::std::ops::BitOrAssign for AssetFlags {
  #[inline]
  fn bitor_assign(&mut self, rhs: AssetFlags) {
    self.0 |= rhs.0;
  }
}
impl ::std::ops::BitAnd<AssetFlags> for AssetFlags {
  type Output = Self;
  #[inline]
  fn bitand(self, other: Self) -> Self {
    AssetFlags(self.0 & other.0)
  }
}
impl ::std::ops::BitAndAssign for AssetFlags {
  #[inline]
  fn bitand_assign(&mut self, rhs: AssetFlags) {
    self.0 &= rhs.0;
  }
}
#[repr(transparent)]
#[derive(Debug, Copy, Clone, Hash, PartialEq, Eq)]
pub struct AssetFlags(pub u32);
impl EnvironmentFlags {
  pub const IS_LIBRARY: EnvironmentFlags = EnvironmentFlags(1);
  pub const SHOULD_OPTIMIZE: EnvironmentFlags = EnvironmentFlags(2);
  pub const SHOULD_SCOPE_HOIST: EnvironmentFlags = EnvironmentFlags(4);
  pub const MODULE_TYPE_EXTENSION: EnvironmentFlags = EnvironmentFlags(8);
}
impl ::std::ops::BitOr<EnvironmentFlags> for EnvironmentFlags {
  type Output = Self;
  #[inline]
  fn bitor(self, other: Self) -> Self {
    EnvironmentFlags(self.0 | other.0)
  }
}
impl ::std::ops::BitOrAssign for EnvironmentFlags {
  #[inline]
  fn bitor_assign(&mut self, rhs: EnvironmentFlags) {
    self.0 |= rhs.0;
  }
}
impl ::std::ops::BitAnd<EnvironmentFlags> for EnvironmentFlags {
  type Output = Self;
  #[inline]
  fn bitand(self, other: Self) -> Self {
    EnvironmentFlags(self.0 & other.0)
  }
}
impl ::std::ops::BitAndAssign for EnvironmentFlags {
  #[inline]
  fn bitand_assign(&mut self, rhs: EnvironmentFlags) {
    self.0 &= rhs.0;
  }
}
#[repr(transparent)]
#[derive(Debug, Copy, Clone, Hash, PartialEq, Eq)]
pub struct EnvironmentFlags(pub u8);
impl BundleFlags {
  pub const NEEDS_STABLE_NAME: BundleFlags = BundleFlags(1);
  pub const IS_SPLITTABLE: BundleFlags = BundleFlags(2);
  pub const IS_PLACEHOLDER: BundleFlags = BundleFlags(4);
  pub const ENTRY: BundleFlags = BundleFlags(8);
}
impl ::std::ops::BitOr<BundleFlags> for BundleFlags {
  type Output = Self;
  #[inline]
  fn bitor(self, other: Self) -> Self {
    BundleFlags(self.0 | other.0)
  }
}
impl ::std::ops::BitOrAssign for BundleFlags {
  #[inline]
  fn bitor_assign(&mut self, rhs: BundleFlags) {
    self.0 |= rhs.0;
  }
}
impl ::std::ops::BitAnd<BundleFlags> for BundleFlags {
  type Output = Self;
  #[inline]
  fn bitand(self, other: Self) -> Self {
    BundleFlags(self.0 & other.0)
  }
}
impl ::std::ops::BitAndAssign for BundleFlags {
  #[inline]
  fn bitand_assign(&mut self, rhs: BundleFlags) {
    self.0 &= rhs.0;
  }
}
#[repr(transparent)]
#[derive(Debug, Copy, Clone, Hash, PartialEq, Eq)]
pub struct BundleFlags(pub u8);
#[doc = " Index of an asset within the bundle graph."]
pub type AssetIndex = u32;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct ParcelApiHeader {
  #[doc = " `size_of::<ParcelApi>()` as the host was built. Always the first member."]
  pub size: usize,
  #[doc = " [`PARCEL_ABI_VERSION`] as the host was built."]
  pub abi: u32,
  #[doc = " Room for a minor version, should appended functions ever need to be\n detectable by something more readable than `size`."]
  pub _reserved: u32,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
  ["Size of ParcelApiHeader"][::std::mem::size_of::<ParcelApiHeader>() - 16usize];
  ["Alignment of ParcelApiHeader"][::std::mem::align_of::<ParcelApiHeader>() - 8usize];
  ["Offset of field: ParcelApiHeader::size"]
    [::std::mem::offset_of!(ParcelApiHeader, size) - 0usize];
  ["Offset of field: ParcelApiHeader::abi"][::std::mem::offset_of!(ParcelApiHeader, abi) - 8usize];
  ["Offset of field: ParcelApiHeader::_reserved"]
    [::std::mem::offset_of!(ParcelApiHeader, _reserved) - 12usize];
};
#[doc = " Byte buffer owned by Parcel.\n Plugins may allocate a buffer with `parcel_buffer_alloc` and release with `parcel_free_buffer()`.\n Use `parcel_buffer_write` or `parcel_buffer_write_utf8` to copy data into an existing Buffer,\n replacing and dropping the existing content if any. Do not set the fields in this struct manually."]
#[repr(C)]
#[derive(Debug)]
pub struct Buffer {
  pub data: *mut u8,
  pub len: usize,
  pub cap: usize,
  pub is_utf8: bool,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
  ["Size of Buffer"][::std::mem::size_of::<Buffer>() - 32usize];
  ["Alignment of Buffer"][::std::mem::align_of::<Buffer>() - 8usize];
  ["Offset of field: Buffer::data"][::std::mem::offset_of!(Buffer, data) - 0usize];
  ["Offset of field: Buffer::len"][::std::mem::offset_of!(Buffer, len) - 8usize];
  ["Offset of field: Buffer::cap"][::std::mem::offset_of!(Buffer, cap) - 16usize];
  ["Offset of field: Buffer::is_utf8"][::std::mem::offset_of!(Buffer, is_utf8) - 24usize];
};
#[doc = " Opaque handle to a Parcel asset. Pass to `parcel_asset_*` functions."]
pub type Asset = u64;
#[doc = " Diagnostic written by a plugin to report an error or warning.\n The host zero-initialises this before every plugin call.\n Fill via `parcel_buffer_alloc()`; host frees all `Buffer` fields after the call.\n If `message.data == NULL` after the call, no diagnostic was set."]
#[repr(C)]
#[derive(Debug)]
pub struct Diagnostic {
  pub message: Buffer,
  pub file_path: Buffer,
  pub line: u32,
  pub column: u32,
  pub hint: Buffer,
  #[doc = " `PARCEL_SEVERITY_*`"]
  pub severity: DiagnosticSeverity,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
  ["Size of Diagnostic"][::std::mem::size_of::<Diagnostic>() - 112usize];
  ["Alignment of Diagnostic"][::std::mem::align_of::<Diagnostic>() - 8usize];
  ["Offset of field: Diagnostic::message"][::std::mem::offset_of!(Diagnostic, message) - 0usize];
  ["Offset of field: Diagnostic::file_path"]
    [::std::mem::offset_of!(Diagnostic, file_path) - 32usize];
  ["Offset of field: Diagnostic::line"][::std::mem::offset_of!(Diagnostic, line) - 64usize];
  ["Offset of field: Diagnostic::column"][::std::mem::offset_of!(Diagnostic, column) - 68usize];
  ["Offset of field: Diagnostic::hint"][::std::mem::offset_of!(Diagnostic, hint) - 72usize];
  ["Offset of field: Diagnostic::severity"]
    [::std::mem::offset_of!(Diagnostic, severity) - 104usize];
};
#[doc = " Opaque handle to Parcel bundle graph."]
pub type BundleGraph = u64;
#[doc = " Opaque handle to Parcel bundle."]
pub type Bundle = u64;
#[doc = " Opaque handle to Parcel build options. Passed to all plugin entry points."]
pub type Options = u64;
#[doc = " Opaque handle to a Parcel target. Obtained via `parcel_asset_get_target()`."]
pub type Target = u64;
#[doc = " Index of a bundle within the bundle graph."]
pub type BundleIndex = usize;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct BundleGraphDependencyResolution {
  #[doc = " `PARCEL_BUNDLE_GRAPH_RESOLUTION_*`"]
  pub resolution_type: BundleGraphResolutionType,
  #[doc = " Valid only when `resolution_type == PARCEL_BUNDLE_GRAPH_RESOLUTION_ASSET`."]
  pub asset: AssetIndex,
  #[doc = " Valid only when `resolution_type == PARCEL_BUNDLE_GRAPH_RESOLUTION_BUNDLE`."]
  pub bundle: BundleIndex,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
  ["Size of BundleGraphDependencyResolution"]
    [::std::mem::size_of::<BundleGraphDependencyResolution>() - 16usize];
  ["Alignment of BundleGraphDependencyResolution"]
    [::std::mem::align_of::<BundleGraphDependencyResolution>() - 8usize];
  ["Offset of field: BundleGraphDependencyResolution::resolution_type"]
    [::std::mem::offset_of!(BundleGraphDependencyResolution, resolution_type) - 0usize];
  ["Offset of field: BundleGraphDependencyResolution::asset"]
    [::std::mem::offset_of!(BundleGraphDependencyResolution, asset) - 4usize];
  ["Offset of field: BundleGraphDependencyResolution::bundle"]
    [::std::mem::offset_of!(BundleGraphDependencyResolution, bundle) - 8usize];
};
#[doc = " Opaque handle to a Parcel dependency. Passed to `parcel_plugin_resolve()`."]
pub type Dependency = u64;
#[doc = " Dependency descriptor passed to `parcel_asset_add_dependency()`.\n Use `PARCEL_SPECIFIER_ESM` / `PARCEL_PRIORITY_SYNC` / `PARCEL_BUNDLE_BEHAVIOR_NONE` as defaults."]
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct DependencyOptions {
  #[doc = " Module specifier bytes (e.g. `\"./foo.js\"`). Required."]
  pub specifier: *const u8,
  #[doc = " Byte length of `specifier`."]
  pub specifier_len: usize,
  #[doc = " `PARCEL_SPECIFIER_*`"]
  pub specifier_type: SpecifierType,
  #[doc = " `PARCEL_PRIORITY_*`"]
  pub priority: Priority,
  #[doc = " `PARCEL_BUNDLE_BEHAVIOR_*`"]
  pub bundle_behavior: BundleBehavior,
  #[doc = " `PARCEL_DEP_*` bits"]
  pub flags: DependencyFlags,
  #[doc = " `PARCEL_EXPORTS_CONDITION_*` bits"]
  pub conditions: ExportsConditions,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
  ["Size of DependencyOptions"][::std::mem::size_of::<DependencyOptions>() - 24usize];
  ["Alignment of DependencyOptions"][::std::mem::align_of::<DependencyOptions>() - 8usize];
  ["Offset of field: DependencyOptions::specifier"]
    [::std::mem::offset_of!(DependencyOptions, specifier) - 0usize];
  ["Offset of field: DependencyOptions::specifier_len"]
    [::std::mem::offset_of!(DependencyOptions, specifier_len) - 8usize];
  ["Offset of field: DependencyOptions::specifier_type"]
    [::std::mem::offset_of!(DependencyOptions, specifier_type) - 16usize];
  ["Offset of field: DependencyOptions::priority"]
    [::std::mem::offset_of!(DependencyOptions, priority) - 17usize];
  ["Offset of field: DependencyOptions::bundle_behavior"]
    [::std::mem::offset_of!(DependencyOptions, bundle_behavior) - 18usize];
  ["Offset of field: DependencyOptions::flags"]
    [::std::mem::offset_of!(DependencyOptions, flags) - 19usize];
  ["Offset of field: DependencyOptions::conditions"]
    [::std::mem::offset_of!(DependencyOptions, conditions) - 20usize];
};
#[doc = " Opaque handle to the diagnostics attached to a reporter event. Pass to the\n `parcel_diagnostics_*` and `parcel_diagnostic_*` functions."]
pub type Diagnostics = u64;
#[doc = " The host functions available to a plugin."]
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct ParcelApi {
  #[doc = " Size and abi version. Always the first member."]
  pub header: ParcelApiHeader,
  pub asset_get_content:
    ::std::option::Option<unsafe extern "C" fn(buf: *mut Buffer, asset: Asset)>,
  pub asset_get_content_utf8:
    ::std::option::Option<unsafe extern "C" fn(buf: *mut Buffer, asset: Asset)>,
  pub asset_set_content:
    ::std::option::Option<unsafe extern "C" fn(asset: Asset, data: *const u8, len: u32)>,
  pub asset_set_content_utf8:
    ::std::option::Option<unsafe extern "C" fn(asset: Asset, data: *const u8, len: u32)>,
  pub asset_set_custom_content: ::std::option::Option<
    unsafe extern "C" fn(
      asset: Asset,
      ty: *const [::std::os::raw::c_uchar; 16usize],
      content: *mut ::std::os::raw::c_void,
      read: ::std::option::Option<
        unsafe extern "C" fn(
          content: *const ::std::os::raw::c_void,
          buf: *mut Buffer,
          diagnostic: *mut Diagnostic,
        ),
      >,
      package: ::std::option::Option<
        unsafe extern "C" fn(
          content: *const ::std::os::raw::c_void,
          bundle_graph: BundleGraph,
          bundle: Bundle,
          options: Options,
          buf: *mut Buffer,
          diagnostic: *mut Diagnostic,
        ),
      >,
      free: ::std::option::Option<unsafe extern "C" fn(content: *mut ::std::os::raw::c_void)>,
    ),
  >,
  pub asset_get_custom_content: ::std::option::Option<
    unsafe extern "C" fn(
      ty: *mut [u8; 16usize],
      content: *mut *mut ::std::os::raw::c_void,
      asset: Asset,
    ) -> bool,
  >,
  pub asset_get_type: ::std::option::Option<unsafe extern "C" fn(buf: *mut Buffer, asset: Asset)>,
  pub asset_set_type:
    ::std::option::Option<unsafe extern "C" fn(asset: Asset, ty: *const u8, ty_len: usize)>,
  pub asset_get_file_path:
    ::std::option::Option<unsafe extern "C" fn(buf: *mut Buffer, asset: Asset, _options: Options)>,
  pub asset_get_pipeline:
    ::std::option::Option<unsafe extern "C" fn(buf: *mut Buffer, asset: Asset)>,
  pub asset_set_pipeline: ::std::option::Option<
    unsafe extern "C" fn(asset: Asset, pipeline: *const u8, pipeline_len: usize),
  >,
  pub asset_get_bundle_behavior:
    ::std::option::Option<unsafe extern "C" fn(asset: Asset) -> BundleBehavior>,
  pub asset_set_bundle_behavior:
    ::std::option::Option<unsafe extern "C" fn(asset: Asset, behavior: BundleBehavior)>,
  pub asset_get_flags: ::std::option::Option<unsafe extern "C" fn(asset: Asset) -> AssetFlags>,
  pub asset_set_flags: ::std::option::Option<unsafe extern "C" fn(asset: Asset, flags: AssetFlags)>,
  pub asset_get_unique_key:
    ::std::option::Option<unsafe extern "C" fn(buf: *mut Buffer, asset: Asset)>,
  pub asset_set_unique_key:
    ::std::option::Option<unsafe extern "C" fn(asset: Asset, key: *const u8, key_len: usize)>,
  pub asset_add_export_symbol:
    ::std::option::Option<unsafe extern "C" fn(asset: Asset, name: *const u8, name_len: usize)>,
  pub free_buffer: ::std::option::Option<unsafe extern "C" fn(buf: *mut Buffer)>,
  pub buffer_alloc:
    ::std::option::Option<unsafe extern "C" fn(data: *const u8, len: usize) -> Buffer>,
  pub buffer_write:
    ::std::option::Option<unsafe extern "C" fn(buf: *mut Buffer, data: *const u8, len: usize)>,
  pub buffer_write_utf8:
    ::std::option::Option<unsafe extern "C" fn(buf: *mut Buffer, data: *const u8, len: usize)>,
  pub bundle_get_type:
    ::std::option::Option<unsafe extern "C" fn(buf: *mut Buffer, bundle: Bundle)>,
  pub bundle_get_target: ::std::option::Option<unsafe extern "C" fn(bundle: Bundle) -> Target>,
  pub bundle_get_bundle_behavior:
    ::std::option::Option<unsafe extern "C" fn(bundle: Bundle) -> BundleBehavior>,
  pub bundle_get_flags: ::std::option::Option<unsafe extern "C" fn(bundle: Bundle) -> BundleFlags>,
  pub bundle_get_dist_path:
    ::std::option::Option<unsafe extern "C" fn(buf: *mut Buffer, bundle: Bundle)>,
  pub bundle_get_asset_count: ::std::option::Option<unsafe extern "C" fn(bundle: Bundle) -> usize>,
  pub bundle_get_asset:
    ::std::option::Option<unsafe extern "C" fn(bundle: Bundle, index: usize) -> AssetIndex>,
  pub bundle_get_entry_asset_count:
    ::std::option::Option<unsafe extern "C" fn(bundle: Bundle) -> usize>,
  pub bundle_get_entry_asset:
    ::std::option::Option<unsafe extern "C" fn(bundle: Bundle, index: usize) -> AssetIndex>,
  pub bundle_get_main_entry_asset:
    ::std::option::Option<unsafe extern "C" fn(bundle: Bundle) -> AssetIndex>,
  pub bundle_get_name:
    ::std::option::Option<unsafe extern "C" fn(buf: *mut Buffer, bundle: Bundle)>,
  pub bundle_get_absolute_url:
    ::std::option::Option<unsafe extern "C" fn(buf: *mut Buffer, bundle: Bundle)>,
  pub bundle_get_relative_url:
    ::std::option::Option<unsafe extern "C" fn(buf: *mut Buffer, bundle: Bundle, from: Bundle)>,
  pub bundle_get_relative_specifier:
    ::std::option::Option<unsafe extern "C" fn(buf: *mut Buffer, bundle: Bundle, from: Bundle)>,
  pub bundle_graph_get_asset_count:
    ::std::option::Option<unsafe extern "C" fn(bundle_graph: BundleGraph) -> usize>,
  pub bundle_graph_get_asset: ::std::option::Option<
    unsafe extern "C" fn(bundle_graph: BundleGraph, index: AssetIndex) -> Asset,
  >,
  pub bundle_graph_get_bundle_count:
    ::std::option::Option<unsafe extern "C" fn(bundle_graph: BundleGraph) -> usize>,
  pub bundle_graph_get_bundle: ::std::option::Option<
    unsafe extern "C" fn(bundle_graph: BundleGraph, index: BundleIndex) -> Bundle,
  >,
  pub bundle_graph_get_dependency_resolution: ::std::option::Option<
    unsafe extern "C" fn(
      bundle_graph: BundleGraph,
      asset: AssetIndex,
      dependency_index: usize,
    ) -> BundleGraphDependencyResolution,
  >,
  pub asset_get_dependency_count:
    ::std::option::Option<unsafe extern "C" fn(asset: Asset) -> usize>,
  pub asset_get_dependency:
    ::std::option::Option<unsafe extern "C" fn(asset: Asset, index: usize) -> Dependency>,
  pub asset_add_dependency:
    ::std::option::Option<unsafe extern "C" fn(asset: Asset, dep: *const DependencyOptions)>,
  pub dep_get_specifier:
    ::std::option::Option<unsafe extern "C" fn(buf: *mut Buffer, dep: Dependency)>,
  pub dep_get_specifier_type:
    ::std::option::Option<unsafe extern "C" fn(dep: Dependency) -> SpecifierType>,
  pub dep_get_priority: ::std::option::Option<unsafe extern "C" fn(dep: Dependency) -> Priority>,
  pub dep_get_bundle_behavior:
    ::std::option::Option<unsafe extern "C" fn(dep: Dependency) -> BundleBehavior>,
  pub dep_get_flags:
    ::std::option::Option<unsafe extern "C" fn(dep: Dependency) -> DependencyFlags>,
  pub dep_get_conditions:
    ::std::option::Option<unsafe extern "C" fn(dep: Dependency) -> ExportsConditions>,
  pub dep_get_source_path: ::std::option::Option<
    unsafe extern "C" fn(buf: *mut Buffer, dep: Dependency, _options: Options),
  >,
  pub dep_get_resolve_from: ::std::option::Option<
    unsafe extern "C" fn(buf: *mut Buffer, dep: Dependency, _options: Options),
  >,
  pub dep_get_target: ::std::option::Option<unsafe extern "C" fn(dep: Dependency) -> Target>,
  pub options_get_project_root:
    ::std::option::Option<unsafe extern "C" fn(buf: *mut Buffer, options: Options)>,
  pub options_get_env: ::std::option::Option<
    unsafe extern "C" fn(buf: *mut Buffer, options: Options, key: *const u8, key_len: usize),
  >,
  pub asset_get_target: ::std::option::Option<unsafe extern "C" fn(asset: Asset) -> Target>,
  pub target_get_environment:
    ::std::option::Option<unsafe extern "C" fn(target: Target) -> Environment>,
  pub target_get_output_format:
    ::std::option::Option<unsafe extern "C" fn(target: Target) -> OutputFormat>,
  pub target_get_source_type:
    ::std::option::Option<unsafe extern "C" fn(target: Target) -> SourceType>,
  pub target_get_env_flags:
    ::std::option::Option<unsafe extern "C" fn(target: Target) -> EnvironmentFlags>,
  pub target_get_public_url:
    ::std::option::Option<unsafe extern "C" fn(buf: *mut Buffer, target: Target)>,
  pub target_get_dist_dir: ::std::option::Option<
    unsafe extern "C" fn(buf: *mut Buffer, target: Target, _options: Options),
  >,
  pub asset_get_query: ::std::option::Option<unsafe extern "C" fn(buf: *mut Buffer, asset: Asset)>,
  pub diagnostics_get_count:
    ::std::option::Option<unsafe extern "C" fn(diagnostics: Diagnostics) -> usize>,
  pub diagnostic_get_message: ::std::option::Option<
    unsafe extern "C" fn(buf: *mut Buffer, diagnostics: Diagnostics, index: usize),
  >,
  pub diagnostic_get_severity: ::std::option::Option<
    unsafe extern "C" fn(diagnostics: Diagnostics, index: usize) -> DiagnosticSeverity,
  >,
  pub diagnostic_get_origin: ::std::option::Option<
    unsafe extern "C" fn(buf: *mut Buffer, diagnostics: Diagnostics, index: usize),
  >,
  pub diagnostic_get_hint_count:
    ::std::option::Option<unsafe extern "C" fn(diagnostics: Diagnostics, index: usize) -> usize>,
  pub diagnostic_get_hint: ::std::option::Option<
    unsafe extern "C" fn(buf: *mut Buffer, diagnostics: Diagnostics, index: usize, hint: usize),
  >,
  pub options_log: ::std::option::Option<
    unsafe extern "C" fn(options: Options, level: LogLevel, message: *const u8, message_len: usize),
  >,
  pub options_log_diagnostic:
    ::std::option::Option<unsafe extern "C" fn(options: Options, diagnostic: *const Diagnostic)>,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
  ["Size of ParcelApi"][::std::mem::size_of::<ParcelApi>() - 584usize];
  ["Alignment of ParcelApi"][::std::mem::align_of::<ParcelApi>() - 8usize];
  ["Offset of field: ParcelApi::header"][::std::mem::offset_of!(ParcelApi, header) - 0usize];
  ["Offset of field: ParcelApi::asset_get_content"]
    [::std::mem::offset_of!(ParcelApi, asset_get_content) - 16usize];
  ["Offset of field: ParcelApi::asset_get_content_utf8"]
    [::std::mem::offset_of!(ParcelApi, asset_get_content_utf8) - 24usize];
  ["Offset of field: ParcelApi::asset_set_content"]
    [::std::mem::offset_of!(ParcelApi, asset_set_content) - 32usize];
  ["Offset of field: ParcelApi::asset_set_content_utf8"]
    [::std::mem::offset_of!(ParcelApi, asset_set_content_utf8) - 40usize];
  ["Offset of field: ParcelApi::asset_set_custom_content"]
    [::std::mem::offset_of!(ParcelApi, asset_set_custom_content) - 48usize];
  ["Offset of field: ParcelApi::asset_get_custom_content"]
    [::std::mem::offset_of!(ParcelApi, asset_get_custom_content) - 56usize];
  ["Offset of field: ParcelApi::asset_get_type"]
    [::std::mem::offset_of!(ParcelApi, asset_get_type) - 64usize];
  ["Offset of field: ParcelApi::asset_set_type"]
    [::std::mem::offset_of!(ParcelApi, asset_set_type) - 72usize];
  ["Offset of field: ParcelApi::asset_get_file_path"]
    [::std::mem::offset_of!(ParcelApi, asset_get_file_path) - 80usize];
  ["Offset of field: ParcelApi::asset_get_pipeline"]
    [::std::mem::offset_of!(ParcelApi, asset_get_pipeline) - 88usize];
  ["Offset of field: ParcelApi::asset_set_pipeline"]
    [::std::mem::offset_of!(ParcelApi, asset_set_pipeline) - 96usize];
  ["Offset of field: ParcelApi::asset_get_bundle_behavior"]
    [::std::mem::offset_of!(ParcelApi, asset_get_bundle_behavior) - 104usize];
  ["Offset of field: ParcelApi::asset_set_bundle_behavior"]
    [::std::mem::offset_of!(ParcelApi, asset_set_bundle_behavior) - 112usize];
  ["Offset of field: ParcelApi::asset_get_flags"]
    [::std::mem::offset_of!(ParcelApi, asset_get_flags) - 120usize];
  ["Offset of field: ParcelApi::asset_set_flags"]
    [::std::mem::offset_of!(ParcelApi, asset_set_flags) - 128usize];
  ["Offset of field: ParcelApi::asset_get_unique_key"]
    [::std::mem::offset_of!(ParcelApi, asset_get_unique_key) - 136usize];
  ["Offset of field: ParcelApi::asset_set_unique_key"]
    [::std::mem::offset_of!(ParcelApi, asset_set_unique_key) - 144usize];
  ["Offset of field: ParcelApi::asset_add_export_symbol"]
    [::std::mem::offset_of!(ParcelApi, asset_add_export_symbol) - 152usize];
  ["Offset of field: ParcelApi::free_buffer"]
    [::std::mem::offset_of!(ParcelApi, free_buffer) - 160usize];
  ["Offset of field: ParcelApi::buffer_alloc"]
    [::std::mem::offset_of!(ParcelApi, buffer_alloc) - 168usize];
  ["Offset of field: ParcelApi::buffer_write"]
    [::std::mem::offset_of!(ParcelApi, buffer_write) - 176usize];
  ["Offset of field: ParcelApi::buffer_write_utf8"]
    [::std::mem::offset_of!(ParcelApi, buffer_write_utf8) - 184usize];
  ["Offset of field: ParcelApi::bundle_get_type"]
    [::std::mem::offset_of!(ParcelApi, bundle_get_type) - 192usize];
  ["Offset of field: ParcelApi::bundle_get_target"]
    [::std::mem::offset_of!(ParcelApi, bundle_get_target) - 200usize];
  ["Offset of field: ParcelApi::bundle_get_bundle_behavior"]
    [::std::mem::offset_of!(ParcelApi, bundle_get_bundle_behavior) - 208usize];
  ["Offset of field: ParcelApi::bundle_get_flags"]
    [::std::mem::offset_of!(ParcelApi, bundle_get_flags) - 216usize];
  ["Offset of field: ParcelApi::bundle_get_dist_path"]
    [::std::mem::offset_of!(ParcelApi, bundle_get_dist_path) - 224usize];
  ["Offset of field: ParcelApi::bundle_get_asset_count"]
    [::std::mem::offset_of!(ParcelApi, bundle_get_asset_count) - 232usize];
  ["Offset of field: ParcelApi::bundle_get_asset"]
    [::std::mem::offset_of!(ParcelApi, bundle_get_asset) - 240usize];
  ["Offset of field: ParcelApi::bundle_get_entry_asset_count"]
    [::std::mem::offset_of!(ParcelApi, bundle_get_entry_asset_count) - 248usize];
  ["Offset of field: ParcelApi::bundle_get_entry_asset"]
    [::std::mem::offset_of!(ParcelApi, bundle_get_entry_asset) - 256usize];
  ["Offset of field: ParcelApi::bundle_get_main_entry_asset"]
    [::std::mem::offset_of!(ParcelApi, bundle_get_main_entry_asset) - 264usize];
  ["Offset of field: ParcelApi::bundle_get_name"]
    [::std::mem::offset_of!(ParcelApi, bundle_get_name) - 272usize];
  ["Offset of field: ParcelApi::bundle_get_absolute_url"]
    [::std::mem::offset_of!(ParcelApi, bundle_get_absolute_url) - 280usize];
  ["Offset of field: ParcelApi::bundle_get_relative_url"]
    [::std::mem::offset_of!(ParcelApi, bundle_get_relative_url) - 288usize];
  ["Offset of field: ParcelApi::bundle_get_relative_specifier"]
    [::std::mem::offset_of!(ParcelApi, bundle_get_relative_specifier) - 296usize];
  ["Offset of field: ParcelApi::bundle_graph_get_asset_count"]
    [::std::mem::offset_of!(ParcelApi, bundle_graph_get_asset_count) - 304usize];
  ["Offset of field: ParcelApi::bundle_graph_get_asset"]
    [::std::mem::offset_of!(ParcelApi, bundle_graph_get_asset) - 312usize];
  ["Offset of field: ParcelApi::bundle_graph_get_bundle_count"]
    [::std::mem::offset_of!(ParcelApi, bundle_graph_get_bundle_count) - 320usize];
  ["Offset of field: ParcelApi::bundle_graph_get_bundle"]
    [::std::mem::offset_of!(ParcelApi, bundle_graph_get_bundle) - 328usize];
  ["Offset of field: ParcelApi::bundle_graph_get_dependency_resolution"]
    [::std::mem::offset_of!(ParcelApi, bundle_graph_get_dependency_resolution) - 336usize];
  ["Offset of field: ParcelApi::asset_get_dependency_count"]
    [::std::mem::offset_of!(ParcelApi, asset_get_dependency_count) - 344usize];
  ["Offset of field: ParcelApi::asset_get_dependency"]
    [::std::mem::offset_of!(ParcelApi, asset_get_dependency) - 352usize];
  ["Offset of field: ParcelApi::asset_add_dependency"]
    [::std::mem::offset_of!(ParcelApi, asset_add_dependency) - 360usize];
  ["Offset of field: ParcelApi::dep_get_specifier"]
    [::std::mem::offset_of!(ParcelApi, dep_get_specifier) - 368usize];
  ["Offset of field: ParcelApi::dep_get_specifier_type"]
    [::std::mem::offset_of!(ParcelApi, dep_get_specifier_type) - 376usize];
  ["Offset of field: ParcelApi::dep_get_priority"]
    [::std::mem::offset_of!(ParcelApi, dep_get_priority) - 384usize];
  ["Offset of field: ParcelApi::dep_get_bundle_behavior"]
    [::std::mem::offset_of!(ParcelApi, dep_get_bundle_behavior) - 392usize];
  ["Offset of field: ParcelApi::dep_get_flags"]
    [::std::mem::offset_of!(ParcelApi, dep_get_flags) - 400usize];
  ["Offset of field: ParcelApi::dep_get_conditions"]
    [::std::mem::offset_of!(ParcelApi, dep_get_conditions) - 408usize];
  ["Offset of field: ParcelApi::dep_get_source_path"]
    [::std::mem::offset_of!(ParcelApi, dep_get_source_path) - 416usize];
  ["Offset of field: ParcelApi::dep_get_resolve_from"]
    [::std::mem::offset_of!(ParcelApi, dep_get_resolve_from) - 424usize];
  ["Offset of field: ParcelApi::dep_get_target"]
    [::std::mem::offset_of!(ParcelApi, dep_get_target) - 432usize];
  ["Offset of field: ParcelApi::options_get_project_root"]
    [::std::mem::offset_of!(ParcelApi, options_get_project_root) - 440usize];
  ["Offset of field: ParcelApi::options_get_env"]
    [::std::mem::offset_of!(ParcelApi, options_get_env) - 448usize];
  ["Offset of field: ParcelApi::asset_get_target"]
    [::std::mem::offset_of!(ParcelApi, asset_get_target) - 456usize];
  ["Offset of field: ParcelApi::target_get_environment"]
    [::std::mem::offset_of!(ParcelApi, target_get_environment) - 464usize];
  ["Offset of field: ParcelApi::target_get_output_format"]
    [::std::mem::offset_of!(ParcelApi, target_get_output_format) - 472usize];
  ["Offset of field: ParcelApi::target_get_source_type"]
    [::std::mem::offset_of!(ParcelApi, target_get_source_type) - 480usize];
  ["Offset of field: ParcelApi::target_get_env_flags"]
    [::std::mem::offset_of!(ParcelApi, target_get_env_flags) - 488usize];
  ["Offset of field: ParcelApi::target_get_public_url"]
    [::std::mem::offset_of!(ParcelApi, target_get_public_url) - 496usize];
  ["Offset of field: ParcelApi::target_get_dist_dir"]
    [::std::mem::offset_of!(ParcelApi, target_get_dist_dir) - 504usize];
  ["Offset of field: ParcelApi::asset_get_query"]
    [::std::mem::offset_of!(ParcelApi, asset_get_query) - 512usize];
  ["Offset of field: ParcelApi::diagnostics_get_count"]
    [::std::mem::offset_of!(ParcelApi, diagnostics_get_count) - 520usize];
  ["Offset of field: ParcelApi::diagnostic_get_message"]
    [::std::mem::offset_of!(ParcelApi, diagnostic_get_message) - 528usize];
  ["Offset of field: ParcelApi::diagnostic_get_severity"]
    [::std::mem::offset_of!(ParcelApi, diagnostic_get_severity) - 536usize];
  ["Offset of field: ParcelApi::diagnostic_get_origin"]
    [::std::mem::offset_of!(ParcelApi, diagnostic_get_origin) - 544usize];
  ["Offset of field: ParcelApi::diagnostic_get_hint_count"]
    [::std::mem::offset_of!(ParcelApi, diagnostic_get_hint_count) - 552usize];
  ["Offset of field: ParcelApi::diagnostic_get_hint"]
    [::std::mem::offset_of!(ParcelApi, diagnostic_get_hint) - 560usize];
  ["Offset of field: ParcelApi::options_log"]
    [::std::mem::offset_of!(ParcelApi, options_log) - 568usize];
  ["Offset of field: ParcelApi::options_log_diagnostic"]
    [::std::mem::offset_of!(ParcelApi, options_log_diagnostic) - 576usize];
};
#[doc = " Result filled by a resolver plugin's `parcel_plugin_resolve()`.\n The struct is zero-initialised by the host before the call.\n\n When type == PARCEL_RESOLUTION_FILE_PATH, fill `file_path` (and optionally `pipeline`) via `parcel_buffer_alloc()`."]
#[repr(C)]
#[derive(Debug)]
pub struct ResolveResult {
  #[doc = " `PARCEL_RESOLUTION_*`"]
  pub resolution_type: ResolutionType,
  pub file_path: Buffer,
  pub pipeline: Buffer,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
  ["Size of ResolveResult"][::std::mem::size_of::<ResolveResult>() - 72usize];
  ["Alignment of ResolveResult"][::std::mem::align_of::<ResolveResult>() - 8usize];
  ["Offset of field: ResolveResult::resolution_type"]
    [::std::mem::offset_of!(ResolveResult, resolution_type) - 0usize];
  ["Offset of field: ResolveResult::file_path"]
    [::std::mem::offset_of!(ResolveResult, file_path) - 8usize];
  ["Offset of field: ResolveResult::pipeline"]
    [::std::mem::offset_of!(ResolveResult, pipeline) - 40usize];
};
#[doc = " Result filled by an optimizer plugin's `parcel_plugin_optimize()`.\n The struct is zero-initialised by the host before the call. Fill `contents`\n and optionally `source_map` using `parcel_buffer_write()` or\n `parcel_buffer_write_utf8()`."]
#[repr(C)]
#[derive(Debug)]
pub struct OptimizeResult {
  pub contents: Buffer,
  #[doc = " Leave empty to remove the source map from the optimized output."]
  pub source_map: Buffer,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
  ["Size of OptimizeResult"][::std::mem::size_of::<OptimizeResult>() - 64usize];
  ["Alignment of OptimizeResult"][::std::mem::align_of::<OptimizeResult>() - 8usize];
  ["Offset of field: OptimizeResult::contents"]
    [::std::mem::offset_of!(OptimizeResult, contents) - 0usize];
  ["Offset of field: OptimizeResult::source_map"]
    [::std::mem::offset_of!(OptimizeResult, source_map) - 32usize];
};
#[doc = " An event passed to a reporter plugin's `parcel_plugin_report()`.\n\n Which fields are filled in depends on `event_type`; the rest are zeroed.\n Every handle and pointer here is valid only for the duration of the call.\n\n Check `size` before reading a field this header declares but an older Parcel\n may not have written. Unlike `ParcelApi`, whose `size` a plugin verifies once\n at startup, this struct is filled in per call and carries its own."]
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct ReportEvent {
  #[doc = " `sizeof(struct ReportEvent)` as the host was built."]
  pub size: usize,
  pub event_type: ReportEventType,
  #[doc = " `PARCEL_EVENT_LOG` only."]
  pub level: LogLevel,
  #[doc = " `PARCEL_EVENT_LOG` only, and NULL when the event carries diagnostics\n instead of a message. Not NUL-terminated; use `message_len`."]
  pub message: *const u8,
  pub message_len: usize,
  #[doc = " `PARCEL_EVENT_BUILD_FAILURE` and `PARCEL_EVENT_LOG`. 0 when the event\n carries no diagnostics."]
  pub diagnostics: Diagnostics,
  #[doc = " `PARCEL_EVENT_BUILD_SUCCESS` only; 0 otherwise."]
  pub bundle_graph: BundleGraph,
  #[doc = " `PARCEL_EVENT_BUILD_SUCCESS` only. How long the build took."]
  pub build_time_ms: u64,
  #[doc = " `PARCEL_EVENT_BUILD_SUCCESS` only. The assets re-transformed by this\n build; empty after a full build, which transformed all of them."]
  pub changed_assets: *const AssetIndex,
  pub changed_asset_count: usize,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
  ["Size of ReportEvent"][::std::mem::size_of::<ReportEvent>() - 72usize];
  ["Alignment of ReportEvent"][::std::mem::align_of::<ReportEvent>() - 8usize];
  ["Offset of field: ReportEvent::size"][::std::mem::offset_of!(ReportEvent, size) - 0usize];
  ["Offset of field: ReportEvent::event_type"]
    [::std::mem::offset_of!(ReportEvent, event_type) - 8usize];
  ["Offset of field: ReportEvent::level"][::std::mem::offset_of!(ReportEvent, level) - 9usize];
  ["Offset of field: ReportEvent::message"][::std::mem::offset_of!(ReportEvent, message) - 16usize];
  ["Offset of field: ReportEvent::message_len"]
    [::std::mem::offset_of!(ReportEvent, message_len) - 24usize];
  ["Offset of field: ReportEvent::diagnostics"]
    [::std::mem::offset_of!(ReportEvent, diagnostics) - 32usize];
  ["Offset of field: ReportEvent::bundle_graph"]
    [::std::mem::offset_of!(ReportEvent, bundle_graph) - 40usize];
  ["Offset of field: ReportEvent::build_time_ms"]
    [::std::mem::offset_of!(ReportEvent, build_time_ms) - 48usize];
  ["Offset of field: ReportEvent::changed_assets"]
    [::std::mem::offset_of!(ReportEvent, changed_assets) - 56usize];
  ["Offset of field: ReportEvent::changed_asset_count"]
    [::std::mem::offset_of!(ReportEvent, changed_asset_count) - 64usize];
};
