/* automatically generated by rust-bindgen 0.70.1 */

pub const PARCEL_INVALID_ASSET_INDEX: u32 = 4294967295;
#[repr(u8)]
#[derive(Debug, Copy, Clone, Hash, PartialEq, Eq)]
pub enum DiagnosticSeverity {
  Error = 0,
  Warning = 1,
  SourceError = 2,
  Info = 3,
}
#[repr(u8)]
#[derive(Debug, Copy, Clone, Hash, PartialEq, Eq)]
pub enum BundleGraphResolutionType {
  Invalid = 0,
  None = 1,
  Deferred = 2,
  External = 3,
  Excluded = 4,
  Asset = 5,
  Bundle = 6,
}
#[repr(u8)]
#[derive(Debug, Copy, Clone, Hash, PartialEq, Eq)]
pub enum BundleBehavior {
  None = 0,
  Inline = 1,
  Isolated = 2,
}
#[repr(u8)]
#[derive(Debug, Copy, Clone, Hash, PartialEq, Eq)]
pub enum Environment {
  Browser = 0,
  WebWorker = 1,
  ServiceWorker = 2,
  Worklet = 3,
  Node = 4,
  ElectronMain = 5,
  ElectronRenderer = 6,
  ReactClient = 7,
  ReactServer = 8,
}
#[repr(u8)]
#[derive(Debug, Copy, Clone, Hash, PartialEq, Eq)]
pub enum OutputFormat {
  Global = 0,
  Commonjs = 1,
  Esmodule = 2,
}
#[repr(u8)]
#[derive(Debug, Copy, Clone, Hash, PartialEq, Eq)]
pub enum SourceType {
  Module = 0,
  Script = 1,
}
#[repr(u8)]
#[derive(Debug, Copy, Clone, Hash, PartialEq, Eq)]
pub enum SpecifierType {
  Esm = 0,
  Commonjs = 1,
  Url = 2,
  Custom = 3,
}
#[repr(u8)]
#[derive(Debug, Copy, Clone, Hash, PartialEq, Eq)]
pub enum Priority {
  Sync = 0,
  Parallel = 1,
  Lazy = 2,
}
#[repr(u8)]
#[derive(Debug, Copy, Clone, Hash, PartialEq, Eq)]
pub enum ResolutionType {
  None = 0,
  FilePath = 1,
  External = 2,
  Excluded = 3,
}
impl DependencyFlags {
  pub const ENTRY: DependencyFlags = DependencyFlags(1);
}
impl DependencyFlags {
  pub const OPTIONAL: DependencyFlags = DependencyFlags(2);
}
impl DependencyFlags {
  pub const NEEDS_STABLE_NAME: DependencyFlags = DependencyFlags(4);
}
impl DependencyFlags {
  pub const IS_WEBWORKER: DependencyFlags = DependencyFlags(8);
}
impl DependencyFlags {
  pub const SIDE_EFFECTS: DependencyFlags = DependencyFlags(16);
}
impl DependencyFlags {
  pub const MACRO: DependencyFlags = DependencyFlags(32);
}
impl ::std::ops::BitOr<DependencyFlags> for DependencyFlags {
  type Output = Self;
  #[inline]
  fn bitor(self, other: Self) -> Self {
    DependencyFlags(self.0 | other.0)
  }
}
impl ::std::ops::BitOrAssign for DependencyFlags {
  #[inline]
  fn bitor_assign(&mut self, rhs: DependencyFlags) {
    self.0 |= rhs.0;
  }
}
impl ::std::ops::BitAnd<DependencyFlags> for DependencyFlags {
  type Output = Self;
  #[inline]
  fn bitand(self, other: Self) -> Self {
    DependencyFlags(self.0 & other.0)
  }
}
impl ::std::ops::BitAndAssign for DependencyFlags {
  #[inline]
  fn bitand_assign(&mut self, rhs: DependencyFlags) {
    self.0 &= rhs.0;
  }
}
#[repr(transparent)]
#[derive(Debug, Copy, Clone, Hash, PartialEq, Eq)]
pub struct DependencyFlags(pub u8);
impl ExportsConditions {
  pub const IMPORT: ExportsConditions = ExportsConditions(1);
}
impl ExportsConditions {
  pub const REQUIRE: ExportsConditions = ExportsConditions(2);
}
impl ExportsConditions {
  pub const MODULE: ExportsConditions = ExportsConditions(4);
}
impl ExportsConditions {
  pub const NODE: ExportsConditions = ExportsConditions(8);
}
impl ExportsConditions {
  pub const BROWSER: ExportsConditions = ExportsConditions(16);
}
impl ExportsConditions {
  pub const WORKER: ExportsConditions = ExportsConditions(32);
}
impl ExportsConditions {
  pub const WORKLET: ExportsConditions = ExportsConditions(64);
}
impl ExportsConditions {
  pub const ELECTRON: ExportsConditions = ExportsConditions(128);
}
impl ExportsConditions {
  pub const DEVELOPMENT: ExportsConditions = ExportsConditions(256);
}
impl ExportsConditions {
  pub const PRODUCTION: ExportsConditions = ExportsConditions(512);
}
impl ExportsConditions {
  pub const TYPES: ExportsConditions = ExportsConditions(1024);
}
impl ExportsConditions {
  pub const DEFAULT: ExportsConditions = ExportsConditions(2048);
}
impl ExportsConditions {
  pub const STYLE: ExportsConditions = ExportsConditions(4096);
}
impl ExportsConditions {
  pub const SASS: ExportsConditions = ExportsConditions(8192);
}
impl ExportsConditions {
  pub const LESS: ExportsConditions = ExportsConditions(16384);
}
impl ExportsConditions {
  pub const STYLUS: ExportsConditions = ExportsConditions(32768);
}
impl ExportsConditions {
  pub const REACT_SERVER: ExportsConditions = ExportsConditions(65536);
}
impl ExportsConditions {
  pub const SOURCE: ExportsConditions = ExportsConditions(131072);
}
impl ::std::ops::BitOr<ExportsConditions> for ExportsConditions {
  type Output = Self;
  #[inline]
  fn bitor(self, other: Self) -> Self {
    ExportsConditions(self.0 | other.0)
  }
}
impl ::std::ops::BitOrAssign for ExportsConditions {
  #[inline]
  fn bitor_assign(&mut self, rhs: ExportsConditions) {
    self.0 |= rhs.0;
  }
}
impl ::std::ops::BitAnd<ExportsConditions> for ExportsConditions {
  type Output = Self;
  #[inline]
  fn bitand(self, other: Self) -> Self {
    ExportsConditions(self.0 & other.0)
  }
}
impl ::std::ops::BitAndAssign for ExportsConditions {
  #[inline]
  fn bitand_assign(&mut self, rhs: ExportsConditions) {
    self.0 &= rhs.0;
  }
}
#[repr(transparent)]
#[doc = " Conditions used when resolving package `exports` and `imports` fields."]
#[derive(Debug, Copy, Clone, Hash, PartialEq, Eq)]
pub struct ExportsConditions(pub u32);
impl AssetFlags {
  pub const IS_SOURCE: AssetFlags = AssetFlags(1);
}
impl AssetFlags {
  pub const SIDE_EFFECTS: AssetFlags = AssetFlags(2);
}
impl AssetFlags {
  pub const IS_BUNDLE_SPLITTABLE: AssetFlags = AssetFlags(4);
}
impl AssetFlags {
  pub const LARGE_BLOB: AssetFlags = AssetFlags(8);
}
impl AssetFlags {
  pub const HAS_CJS_EXPORTS: AssetFlags = AssetFlags(16);
}
impl AssetFlags {
  pub const STATIC_EXPORTS: AssetFlags = AssetFlags(32);
}
impl AssetFlags {
  pub const SHOULD_WRAP: AssetFlags = AssetFlags(64);
}
impl AssetFlags {
  pub const IS_CONSTANT_MODULE: AssetFlags = AssetFlags(128);
}
impl AssetFlags {
  pub const HAS_NODE_REPLACEMENTS: AssetFlags = AssetFlags(256);
}
impl AssetFlags {
  pub const HAS_SYMBOLS: AssetFlags = AssetFlags(512);
}
impl AssetFlags {
  pub const IS_HTML_ATTR: AssetFlags = AssetFlags(1024);
}
impl AssetFlags {
  pub const IS_HTML_TAG: AssetFlags = AssetFlags(2048);
}
impl AssetFlags {
  pub const IS_ESM: AssetFlags = AssetFlags(4096);
}
impl ::std::ops::BitOr<AssetFlags> for AssetFlags {
  type Output = Self;
  #[inline]
  fn bitor(self, other: Self) -> Self {
    AssetFlags(self.0 | other.0)
  }
}
impl ::std::ops::BitOrAssign for AssetFlags {
  #[inline]
  fn bitor_assign(&mut self, rhs: AssetFlags) {
    self.0 |= rhs.0;
  }
}
impl ::std::ops::BitAnd<AssetFlags> for AssetFlags {
  type Output = Self;
  #[inline]
  fn bitand(self, other: Self) -> Self {
    AssetFlags(self.0 & other.0)
  }
}
impl ::std::ops::BitAndAssign for AssetFlags {
  #[inline]
  fn bitand_assign(&mut self, rhs: AssetFlags) {
    self.0 &= rhs.0;
  }
}
#[repr(transparent)]
#[derive(Debug, Copy, Clone, Hash, PartialEq, Eq)]
pub struct AssetFlags(pub u32);
impl EnvironmentFlags {
  pub const IS_LIBRARY: EnvironmentFlags = EnvironmentFlags(1);
}
impl EnvironmentFlags {
  pub const SHOULD_OPTIMIZE: EnvironmentFlags = EnvironmentFlags(2);
}
impl EnvironmentFlags {
  pub const SHOULD_SCOPE_HOIST: EnvironmentFlags = EnvironmentFlags(4);
}
impl EnvironmentFlags {
  pub const MODULE_TYPE_EXTENSION: EnvironmentFlags = EnvironmentFlags(8);
}
impl ::std::ops::BitOr<EnvironmentFlags> for EnvironmentFlags {
  type Output = Self;
  #[inline]
  fn bitor(self, other: Self) -> Self {
    EnvironmentFlags(self.0 | other.0)
  }
}
impl ::std::ops::BitOrAssign for EnvironmentFlags {
  #[inline]
  fn bitor_assign(&mut self, rhs: EnvironmentFlags) {
    self.0 |= rhs.0;
  }
}
impl ::std::ops::BitAnd<EnvironmentFlags> for EnvironmentFlags {
  type Output = Self;
  #[inline]
  fn bitand(self, other: Self) -> Self {
    EnvironmentFlags(self.0 & other.0)
  }
}
impl ::std::ops::BitAndAssign for EnvironmentFlags {
  #[inline]
  fn bitand_assign(&mut self, rhs: EnvironmentFlags) {
    self.0 &= rhs.0;
  }
}
#[repr(transparent)]
#[derive(Debug, Copy, Clone, Hash, PartialEq, Eq)]
pub struct EnvironmentFlags(pub u8);
impl BundleFlags {
  pub const NEEDS_STABLE_NAME: BundleFlags = BundleFlags(1);
}
impl BundleFlags {
  pub const IS_SPLITTABLE: BundleFlags = BundleFlags(2);
}
impl BundleFlags {
  pub const IS_PLACEHOLDER: BundleFlags = BundleFlags(4);
}
impl BundleFlags {
  pub const ENTRY: BundleFlags = BundleFlags(8);
}
impl ::std::ops::BitOr<BundleFlags> for BundleFlags {
  type Output = Self;
  #[inline]
  fn bitor(self, other: Self) -> Self {
    BundleFlags(self.0 | other.0)
  }
}
impl ::std::ops::BitOrAssign for BundleFlags {
  #[inline]
  fn bitor_assign(&mut self, rhs: BundleFlags) {
    self.0 |= rhs.0;
  }
}
impl ::std::ops::BitAnd<BundleFlags> for BundleFlags {
  type Output = Self;
  #[inline]
  fn bitand(self, other: Self) -> Self {
    BundleFlags(self.0 & other.0)
  }
}
impl ::std::ops::BitAndAssign for BundleFlags {
  #[inline]
  fn bitand_assign(&mut self, rhs: BundleFlags) {
    self.0 &= rhs.0;
  }
}
#[repr(transparent)]
#[derive(Debug, Copy, Clone, Hash, PartialEq, Eq)]
pub struct BundleFlags(pub u8);
#[doc = " Byte buffer owned by Parcel.\n Plugins may allocate a buffer with `parcel_buffer_alloc` and release with `parcel_free_buffer()`.\n Use `parcel_buffer_write` or `parcel_buffer_write_utf8` to copy data into an existing Buffer,\n replacing and dropping the existing content if any. Do not set the fields in this struct manually."]
#[repr(C)]
#[derive(Debug)]
pub struct Buffer {
  pub data: *mut u8,
  pub len: usize,
  pub cap: usize,
  pub is_utf8: bool,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
  ["Size of Buffer"][::std::mem::size_of::<Buffer>() - 32usize];
  ["Alignment of Buffer"][::std::mem::align_of::<Buffer>() - 8usize];
  ["Offset of field: Buffer::data"][::std::mem::offset_of!(Buffer, data) - 0usize];
  ["Offset of field: Buffer::len"][::std::mem::offset_of!(Buffer, len) - 8usize];
  ["Offset of field: Buffer::cap"][::std::mem::offset_of!(Buffer, cap) - 16usize];
  ["Offset of field: Buffer::is_utf8"][::std::mem::offset_of!(Buffer, is_utf8) - 24usize];
};
#[doc = " Opaque handle to a Parcel asset. Pass to `parcel_asset_*` functions."]
pub type Asset = u64;
#[doc = " Diagnostic written by a plugin to report an error or warning.\n The host zero-initialises this before every plugin call.\n Fill via `parcel_buffer_alloc()`; host frees all `Buffer` fields after the call.\n If `message.data == NULL` after the call, no diagnostic was set."]
#[repr(C)]
#[derive(Debug)]
pub struct Diagnostic {
  pub message: Buffer,
  pub file_path: Buffer,
  pub line: u32,
  pub column: u32,
  pub hint: Buffer,
  #[doc = " `PARCEL_SEVERITY_*`"]
  pub severity: DiagnosticSeverity,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
  ["Size of Diagnostic"][::std::mem::size_of::<Diagnostic>() - 112usize];
  ["Alignment of Diagnostic"][::std::mem::align_of::<Diagnostic>() - 8usize];
  ["Offset of field: Diagnostic::message"][::std::mem::offset_of!(Diagnostic, message) - 0usize];
  ["Offset of field: Diagnostic::file_path"]
    [::std::mem::offset_of!(Diagnostic, file_path) - 32usize];
  ["Offset of field: Diagnostic::line"][::std::mem::offset_of!(Diagnostic, line) - 64usize];
  ["Offset of field: Diagnostic::column"][::std::mem::offset_of!(Diagnostic, column) - 68usize];
  ["Offset of field: Diagnostic::hint"][::std::mem::offset_of!(Diagnostic, hint) - 72usize];
  ["Offset of field: Diagnostic::severity"]
    [::std::mem::offset_of!(Diagnostic, severity) - 104usize];
};
#[doc = " Opaque handle to Parcel bundle graph."]
pub type BundleGraph = u64;
#[doc = " Opaque handle to Parcel bundle."]
pub type Bundle = u64;
#[doc = " Opaque handle to Parcel build options. Passed to all plugin entry points."]
pub type Options = u64;
#[doc = " Index of an asset within the bundle graph."]
pub type AssetIndex = u32;
#[doc = " Index of a bundle within the bundle graph."]
pub type BundleIndex = usize;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct BundleGraphDependencyResolution {
  #[doc = " `PARCEL_BUNDLE_GRAPH_RESOLUTION_*`"]
  pub resolution_type: BundleGraphResolutionType,
  #[doc = " Valid only when `resolution_type == PARCEL_BUNDLE_GRAPH_RESOLUTION_ASSET`."]
  pub asset: AssetIndex,
  #[doc = " Valid only when `resolution_type == PARCEL_BUNDLE_GRAPH_RESOLUTION_BUNDLE`."]
  pub bundle: BundleIndex,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
  ["Size of BundleGraphDependencyResolution"]
    [::std::mem::size_of::<BundleGraphDependencyResolution>() - 16usize];
  ["Alignment of BundleGraphDependencyResolution"]
    [::std::mem::align_of::<BundleGraphDependencyResolution>() - 8usize];
  ["Offset of field: BundleGraphDependencyResolution::resolution_type"]
    [::std::mem::offset_of!(BundleGraphDependencyResolution, resolution_type) - 0usize];
  ["Offset of field: BundleGraphDependencyResolution::asset"]
    [::std::mem::offset_of!(BundleGraphDependencyResolution, asset) - 4usize];
  ["Offset of field: BundleGraphDependencyResolution::bundle"]
    [::std::mem::offset_of!(BundleGraphDependencyResolution, bundle) - 8usize];
};
#[doc = " Opaque handle to a Parcel target. Obtained via `parcel_asset_get_target()`."]
pub type Target = u64;
#[doc = " Opaque handle to a Parcel dependency. Passed to `parcel_plugin_resolve()`."]
pub type Dependency = u64;
#[doc = " Dependency descriptor passed to `parcel_asset_add_dependency()`.\n Use `PARCEL_SPECIFIER_ESM` / `PARCEL_PRIORITY_SYNC` / `PARCEL_BUNDLE_BEHAVIOR_NONE` as defaults."]
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct DependencyOptions {
  #[doc = " Module specifier bytes (e.g. `\"./foo.js\"`). Required."]
  pub specifier: *const u8,
  #[doc = " Byte length of `specifier`."]
  pub specifier_len: usize,
  #[doc = " `PARCEL_SPECIFIER_*`"]
  pub specifier_type: SpecifierType,
  #[doc = " `PARCEL_PRIORITY_*`"]
  pub priority: Priority,
  #[doc = " `PARCEL_BUNDLE_BEHAVIOR_*`"]
  pub bundle_behavior: BundleBehavior,
  #[doc = " `PARCEL_DEP_*` bits"]
  pub flags: DependencyFlags,
  #[doc = " `PARCEL_EXPORTS_CONDITION_*` bits"]
  pub conditions: ExportsConditions,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
  ["Size of DependencyOptions"][::std::mem::size_of::<DependencyOptions>() - 24usize];
  ["Alignment of DependencyOptions"][::std::mem::align_of::<DependencyOptions>() - 8usize];
  ["Offset of field: DependencyOptions::specifier"]
    [::std::mem::offset_of!(DependencyOptions, specifier) - 0usize];
  ["Offset of field: DependencyOptions::specifier_len"]
    [::std::mem::offset_of!(DependencyOptions, specifier_len) - 8usize];
  ["Offset of field: DependencyOptions::specifier_type"]
    [::std::mem::offset_of!(DependencyOptions, specifier_type) - 16usize];
  ["Offset of field: DependencyOptions::priority"]
    [::std::mem::offset_of!(DependencyOptions, priority) - 17usize];
  ["Offset of field: DependencyOptions::bundle_behavior"]
    [::std::mem::offset_of!(DependencyOptions, bundle_behavior) - 18usize];
  ["Offset of field: DependencyOptions::flags"]
    [::std::mem::offset_of!(DependencyOptions, flags) - 19usize];
  ["Offset of field: DependencyOptions::conditions"]
    [::std::mem::offset_of!(DependencyOptions, conditions) - 20usize];
};
#[doc = " Result filled by a resolver plugin's `parcel_plugin_resolve()`.\n The struct is zero-initialised by the host before the call.\n\n When type == PARCEL_RESOLUTION_FILE_PATH, fill `file_path` (and optionally `pipeline`) via `parcel_buffer_alloc()`."]
#[repr(C)]
#[derive(Debug)]
pub struct ResolveResult {
  #[doc = " `PARCEL_RESOLUTION_*`"]
  pub resolution_type: ResolutionType,
  pub file_path: Buffer,
  pub pipeline: Buffer,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
  ["Size of ResolveResult"][::std::mem::size_of::<ResolveResult>() - 72usize];
  ["Alignment of ResolveResult"][::std::mem::align_of::<ResolveResult>() - 8usize];
  ["Offset of field: ResolveResult::resolution_type"]
    [::std::mem::offset_of!(ResolveResult, resolution_type) - 0usize];
  ["Offset of field: ResolveResult::file_path"]
    [::std::mem::offset_of!(ResolveResult, file_path) - 8usize];
  ["Offset of field: ResolveResult::pipeline"]
    [::std::mem::offset_of!(ResolveResult, pipeline) - 40usize];
};
unsafe extern "C" {
  #[doc = " Release a `Buffer` previously filled by a getter or `parcel_buffer_alloc()`."]
  pub fn parcel_free_buffer(buf: *mut Buffer);
}
unsafe extern "C" {
  #[doc = " Allocates a new `Buffer` containing a copy of `[data, data+len)`.\n The plugin calls this to fill `ResolveResult` or `Diagnostic` fields.\n Returns a zero `Buffer` when `data` is NULL or `len` is 0."]
  pub fn parcel_buffer_alloc(data: *const u8, len: usize) -> Buffer;
}
unsafe extern "C" {
  #[doc = " Copies the given bytes into a `Buffer`, replacing the existing content if any."]
  pub fn parcel_buffer_write(buf: *mut Buffer, data: *const u8, len: usize);
}
unsafe extern "C" {
  #[doc = " Copies the given UTF-8 encoded string into a `Buffer`, replacing the existing content if any.\n It is the caller's responsibility to ensure that the UTF-8 data is valid."]
  pub fn parcel_buffer_write_utf8(buf: *mut Buffer, data: *const u8, len: usize);
}
unsafe extern "C" {
  #[doc = " Returns the asset content into `*buf`. Caller must `parcel_free_buffer(buf)`."]
  pub fn parcel_asset_get_content(buf: *mut Buffer, asset: Asset);
}
unsafe extern "C" {
  #[doc = " Returns the asset content as a UTF-8 string into `*buf`. Caller must `parcel_free_buffer(buf)`."]
  pub fn parcel_asset_get_content_utf8(buf: *mut Buffer, asset: Asset);
}
unsafe extern "C" {
  #[doc = " Replaces the asset content with the given bytes."]
  pub fn parcel_asset_set_content(asset: Asset, data: *const u8, len: u32);
}
unsafe extern "C" {
  #[doc = " Replaces the asset content with the given UTF-8 bytes.\n It is the caller's responsibility to validate that the data is valid UTF-8."]
  pub fn parcel_asset_set_content_utf8(asset: Asset, data: *const u8, len: u32);
}
unsafe extern "C" {
  #[doc = " Replaces the asset content with a custom content type."]
  pub fn parcel_asset_set_custom_content(
    asset: Asset,
    ty: *const [::std::os::raw::c_uchar; 16usize],
    content: *mut ::std::os::raw::c_void,
    read: ::std::option::Option<
      unsafe extern "C" fn(
        content: *const ::std::os::raw::c_void,
        buf: *mut Buffer,
        diagnostic: *mut Diagnostic,
      ),
    >,
    package: ::std::option::Option<
      unsafe extern "C" fn(
        content: *const ::std::os::raw::c_void,
        bundle_graph: BundleGraph,
        bundle: Bundle,
        options: Options,
        buf: *mut Buffer,
        diagnostic: *mut Diagnostic,
      ),
    >,
    free: ::std::option::Option<unsafe extern "C" fn(content: *mut ::std::os::raw::c_void)>,
  );
}
unsafe extern "C" {
  #[doc = " Gets the custom content and type identifier for `asset`. Returns true if the output parameters were set."]
  pub fn parcel_asset_get_custom_content(
    ty: *mut [u8; 16usize],
    content: *mut *mut ::std::os::raw::c_void,
    asset: Asset,
  ) -> bool;
}
unsafe extern "C" {
  #[doc = " Returns the number of assets in the graph."]
  pub fn parcel_bundle_graph_get_asset_count(bundle_graph: BundleGraph) -> usize;
}
unsafe extern "C" {
  #[doc = " Returns a borrowed, read-only asset handle, or zero when `index` is out of bounds.\n The handle is valid only for the lifetime of the bundle graph and must only be\n passed to `parcel_asset_get_*` functions."]
  pub fn parcel_bundle_graph_get_asset(bundle_graph: BundleGraph, index: AssetIndex) -> Asset;
}
unsafe extern "C" {
  #[doc = " Returns the number of bundles in the graph."]
  pub fn parcel_bundle_graph_get_bundle_count(bundle_graph: BundleGraph) -> usize;
}
unsafe extern "C" {
  #[doc = " Returns a borrowed bundle handle, or zero when `index` is out of bounds."]
  pub fn parcel_bundle_graph_get_bundle(bundle_graph: BundleGraph, index: BundleIndex) -> Bundle;
}
unsafe extern "C" {
  #[doc = " Returns the resolution of one dependency belonging to an asset.\n Returns `PARCEL_BUNDLE_GRAPH_RESOLUTION_INVALID` for invalid indices."]
  pub fn parcel_bundle_graph_get_dependency_resolution(
    bundle_graph: BundleGraph,
    asset: AssetIndex,
    dependency_index: usize,
  ) -> BundleGraphDependencyResolution;
}
unsafe extern "C" {
  #[doc = " Returns the bundle type extension (for example, `\"js\"`) into `*buf`."]
  pub fn parcel_bundle_get_type(buf: *mut Buffer, bundle: Bundle);
}
unsafe extern "C" {
  #[doc = " Returns the bundle target as a borrowed handle."]
  pub fn parcel_bundle_get_target(bundle: Bundle) -> Target;
}
unsafe extern "C" {
  #[doc = " Returns the bundle behavior (`PARCEL_BUNDLE_BEHAVIOR_*`)."]
  pub fn parcel_bundle_get_bundle_behavior(bundle: Bundle) -> BundleBehavior;
}
unsafe extern "C" {
  #[doc = " Returns the raw `BundleFlags` bitfield (`PARCEL_BUNDLE_FLAG_*` bits)."]
  pub fn parcel_bundle_get_flags(bundle: Bundle) -> BundleFlags;
}
unsafe extern "C" {
  #[doc = " Returns the absolute output path into `*buf`, or leaves it empty when unnamed."]
  pub fn parcel_bundle_get_dist_path(buf: *mut Buffer, bundle: Bundle);
}
unsafe extern "C" {
  pub fn parcel_bundle_get_asset_count(bundle: Bundle) -> usize;
}
unsafe extern "C" {
  #[doc = " Returns an asset index, or `PARCEL_INVALID_ASSET_INDEX` when out of bounds."]
  pub fn parcel_bundle_get_asset(bundle: Bundle, index: usize) -> AssetIndex;
}
unsafe extern "C" {
  pub fn parcel_bundle_get_entry_asset_count(bundle: Bundle) -> usize;
}
unsafe extern "C" {
  #[doc = " Returns an entry asset index, or `PARCEL_INVALID_ASSET_INDEX` when out of bounds."]
  pub fn parcel_bundle_get_entry_asset(bundle: Bundle, index: usize) -> AssetIndex;
}
unsafe extern "C" {
  #[doc = " Returns the main entry asset, or `PARCEL_INVALID_ASSET_INDEX` when absent."]
  pub fn parcel_bundle_get_main_entry_asset(bundle: Bundle) -> AssetIndex;
}
unsafe extern "C" {
  #[doc = " Returns the dist-relative bundle name into `*buf`, or leaves it empty when unnamed."]
  pub fn parcel_bundle_get_name(buf: *mut Buffer, bundle: Bundle);
}
unsafe extern "C" {
  #[doc = " Returns the public bundle URL into `*buf`, or leaves it empty when unnamed."]
  pub fn parcel_bundle_get_absolute_url(buf: *mut Buffer, bundle: Bundle);
}
unsafe extern "C" {
  #[doc = " Returns `bundle`'s URL relative to `from`, or leaves `*buf` empty when unavailable."]
  pub fn parcel_bundle_get_relative_url(buf: *mut Buffer, bundle: Bundle, from: Bundle);
}
unsafe extern "C" {
  #[doc = " Returns `bundle`'s module specifier relative to `from`, or leaves `*buf` empty when unavailable."]
  pub fn parcel_bundle_get_relative_specifier(buf: *mut Buffer, bundle: Bundle, from: Bundle);
}
unsafe extern "C" {
  #[doc = " Returns the asset type extension (e.g. `\"js\"`, `\"css\"`) into `*buf`.\n Caller must `parcel_free_buffer(buf)`."]
  pub fn parcel_asset_get_type(buf: *mut Buffer, asset: Asset);
}
unsafe extern "C" {
  #[doc = " Changes the asset type to the given file-extension bytes (e.g. `\"js\"`)."]
  pub fn parcel_asset_set_type(asset: Asset, ty: *const u8, ty_len: usize);
}
unsafe extern "C" {
  #[doc = " Returns the absolute filesystem path of the source asset into `*buf`.\n `options` is the handle received from `parcel_plugin_transform()`.\n Caller must `parcel_free_buffer(buf)`."]
  pub fn parcel_asset_get_file_path(buf: *mut Buffer, asset: Asset, _options: Options);
}
unsafe extern "C" {
  #[doc = " Returns the named pipeline into `*buf`, or leaves `buf->data == NULL` if none is set.\n Caller must `parcel_free_buffer(buf)` when `data != NULL`."]
  pub fn parcel_asset_get_pipeline(buf: *mut Buffer, asset: Asset);
}
unsafe extern "C" {
  #[doc = " Sets the named pipeline. Pass `NULL` / `0` to clear."]
  pub fn parcel_asset_set_pipeline(asset: Asset, pipeline: *const u8, pipeline_len: usize);
}
unsafe extern "C" {
  #[doc = " Returns the bundle behavior (`PARCEL_BUNDLE_BEHAVIOR_*`)."]
  pub fn parcel_asset_get_bundle_behavior(asset: Asset) -> BundleBehavior;
}
unsafe extern "C" {
  #[doc = " Sets the bundle behavior (`PARCEL_BUNDLE_BEHAVIOR_*`)."]
  pub fn parcel_asset_set_bundle_behavior(asset: Asset, behavior: BundleBehavior);
}
unsafe extern "C" {
  #[doc = " Returns the raw `AssetFlags` bitfield (`PARCEL_ASSET_*` bits)."]
  pub fn parcel_asset_get_flags(asset: Asset) -> AssetFlags;
}
unsafe extern "C" {
  #[doc = " Replaces the `AssetFlags` bitfield."]
  pub fn parcel_asset_set_flags(asset: Asset, flags: AssetFlags);
}
unsafe extern "C" {
  #[doc = " Returns the unique key into `*buf`, or leaves `buf->data == NULL` if not set.\n Caller must `parcel_free_buffer(buf)` when `data != NULL`."]
  pub fn parcel_asset_get_unique_key(buf: *mut Buffer, asset: Asset);
}
unsafe extern "C" {
  #[doc = " Sets the unique key. Pass `NULL` / `0` to clear."]
  pub fn parcel_asset_set_unique_key(asset: Asset, key: *const u8, key_len: usize);
}
unsafe extern "C" {
  #[doc = " Returns an opaque `Target` handle. Valid for the duration of the transform call."]
  pub fn parcel_asset_get_target(asset: Asset) -> Target;
}
unsafe extern "C" {
  #[doc = " Returns the target environment (`PARCEL_ENV_*`)."]
  pub fn parcel_target_get_environment(target: Target) -> Environment;
}
unsafe extern "C" {
  #[doc = " Returns the output format (`PARCEL_OUTPUT_FORMAT_*`)."]
  pub fn parcel_target_get_output_format(target: Target) -> OutputFormat;
}
unsafe extern "C" {
  #[doc = " Returns the source type (`PARCEL_SOURCE_TYPE_*`)."]
  pub fn parcel_target_get_source_type(target: Target) -> SourceType;
}
unsafe extern "C" {
  #[doc = " Returns the `EnvironmentFlags` bitfield (`PARCEL_ENV_FLAG_*` bits)."]
  pub fn parcel_target_get_env_flags(target: Target) -> EnvironmentFlags;
}
unsafe extern "C" {
  #[doc = " Returns the public URL (e.g. `\"/\"`) into `*buf`. Caller must `parcel_free_buffer(buf)`."]
  pub fn parcel_target_get_public_url(buf: *mut Buffer, target: Target);
}
unsafe extern "C" {
  #[doc = " Returns the absolute path of the dist directory into `*buf`.\n `options` is the handle received from `parcel_plugin_transform()`.\n Caller must `parcel_free_buffer(buf)`."]
  pub fn parcel_target_get_dist_dir(buf: *mut Buffer, target: Target, _options: Options);
}
unsafe extern "C" {
  #[doc = " Returns the number of dependencies belonging to an asset."]
  pub fn parcel_asset_get_dependency_count(asset: Asset) -> usize;
}
unsafe extern "C" {
  #[doc = " Returns a borrowed, read-only dependency handle, or zero when `index` is out of bounds.\n The handle is valid only for the lifetime of the asset."]
  pub fn parcel_asset_get_dependency(asset: Asset, index: usize) -> Dependency;
}
unsafe extern "C" {
  #[doc = " Appends a dependency to the asset. The new dependency inherits the asset's target."]
  pub fn parcel_asset_add_dependency(asset: Asset, dep: *const DependencyOptions);
}
unsafe extern "C" {
  #[doc = " Registers an exported symbol name (e.g. `\"default\"`, `\"foo\"`, `\"*\"`)."]
  pub fn parcel_asset_add_export_symbol(asset: Asset, name: *const u8, name_len: usize);
}
unsafe extern "C" {
  #[doc = " Returns the raw specifier string (e.g. `\"custom:greeting\"`) into `*buf`."]
  pub fn parcel_dep_get_specifier(buf: *mut Buffer, dep: Dependency);
}
unsafe extern "C" {
  #[doc = " Returns the specifier type (`PARCEL_SPECIFIER_*`)."]
  pub fn parcel_dep_get_specifier_type(dep: Dependency) -> SpecifierType;
}
unsafe extern "C" {
  #[doc = " Returns the priority (`PARCEL_PRIORITY_*`)."]
  pub fn parcel_dep_get_priority(dep: Dependency) -> Priority;
}
unsafe extern "C" {
  #[doc = " Returns the bundle behavior (`PARCEL_BUNDLE_BEHAVIOR_*`)."]
  pub fn parcel_dep_get_bundle_behavior(dep: Dependency) -> BundleBehavior;
}
unsafe extern "C" {
  #[doc = " Returns the raw `DependencyFlags` bitfield (`PARCEL_DEP_*` bits)."]
  pub fn parcel_dep_get_flags(dep: Dependency) -> DependencyFlags;
}
unsafe extern "C" {
  #[doc = " Returns the raw `ExportsConditions` bitfield (`PARCEL_EXPORTS_CONDITION_*` bits)."]
  pub fn parcel_dep_get_conditions(dep: Dependency) -> ExportsConditions;
}
unsafe extern "C" {
  #[doc = " Returns the absolute path of the file containing this import into `*buf`."]
  pub fn parcel_dep_get_source_path(buf: *mut Buffer, dep: Dependency, _options: Options);
}
unsafe extern "C" {
  #[doc = " Returns the base path for resolving the specifier into `*buf`.\n Falls back to the source file path when `resolve_from` is not set."]
  pub fn parcel_dep_get_resolve_from(buf: *mut Buffer, dep: Dependency, _options: Options);
}
unsafe extern "C" {
  #[doc = " Returns an opaque `Target` handle for the dependency."]
  pub fn parcel_dep_get_target(dep: Dependency) -> Target;
}
unsafe extern "C" {
  #[doc = " Returns the project root as an absolute filesystem path into `*buf`.\n Caller must `parcel_free_buffer(buf)`."]
  pub fn parcel_options_get_project_root(buf: *mut Buffer, options: Options);
}
unsafe extern "C" {
  #[doc = " Looks up `key` in the build environment map.\n Writes the value into `*buf` if found; leaves `buf->data == NULL` if not.\n Caller must `parcel_free_buffer(buf)` when `data != NULL`."]
  pub fn parcel_options_get_env(buf: *mut Buffer, options: Options, key: *const u8, key_len: usize);
}
