/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export function fileId(name: string): number
export function fileName(fileId: number): string
export interface EnvironmentOpts {
  context: string
  outputFormat: string
  sourceType: string
  isLibrary: boolean
  shouldOptimize: boolean
  shouldScopeHoist: boolean
}
export function createEnvironment(opts: EnvironmentOpts): number
export function environmentIsLibrary(id: number): boolean
export function environmentShouldOptimize(id: number): boolean
export function environmentShouldScopeHoist(id: number): boolean
export function environmentContext(id: number): number
export function environmentOutputFormat(id: number): number
export function environmentSourceType(id: number): number
