/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export function fileId(name: string): number
export function fileName(fileId: number): string
export interface EnvironmentOpts {
  context: string
  outputFormat: string
  sourceType: string
  isLibrary: boolean
  shouldOptimize: boolean
  shouldScopeHoist: boolean
}
export function createEnvironment(opts: EnvironmentOpts): number
export function environmentIsLibrary(id: number): boolean
export function environmentShouldOptimize(id: number): boolean
export function environmentShouldScopeHoist(id: number): boolean
export function environmentContext(id: number): number
export function environmentOutputFormat(id: number): number
export function environmentSourceType(id: number): number
export interface DependencyOptions {
  assetId?: number
  envId: number
  specifier: string
  specifierType: number
  resolveFrom?: number
  priority: number
  bundleBehavior: number
  needsStableName: boolean
  isEntry: boolean
  isOptional: boolean
}
export function createDependency(opts: DependencyOptions): number
export function dependencySpecifier(id: number): string
export function dependencyEnv(id: number): number
export function dependencyResolveFrom(id: number): number | null
export function dependencySpecifierType(id: number): number
export function dependencyPriority(id: number): number
export function dependencyBundleBehavior(id: number): number
export function dependencyIsEntry(id: number): boolean
export function dependencyNeedsStableName(id: number): boolean
export function dependencyIsOptional(id: number): boolean
export interface AssetOptions {
  fileId: number
  envId: number
  contentKey: string
  mapKey?: string
  outputHash: string
  assetType: string
  bundleBehavior: number
  isSource: boolean
  sideEffects: boolean
  isBundleSplittable: boolean
}
export function createAsset(opts: AssetOptions): number
export function assetEnv(id: number): number
export function assetFileId(id: number): number
export function assetBundleBehavior(id: number): number
export function assetIsBundleSplittable(id: number): boolean
export function assetSideEffects(id: number): boolean
export function assetIsSource(id: number): boolean
export function assetContentKey(id: number): string
