language = "C"
include_guard = "PARCEL_PLUGIN_H"
cpp_compat = true
no_includes = true
sys_includes = ["stdint.h", "stdbool.h"]

[export]
include = ["ParcelApi", "InitStatus", "Diagnostic", "ResolveResult", "OptimizeResult", "DependencyFlags", "ExportsConditions", "AssetFlags", "EnvironmentFlags", "BundleFlags", "BundleGraphDependencyResolution", "PARCEL_INVALID_ASSET_INDEX"]
exclude = ["CPlugin", "AssetFlagsFFI", "DependencyFlagsFFI", "ExportsConditionsFFI", "EnvironmentFlagsFFI", "BundleFlagsFFI"]

[export.rename]
"AssetFlagsFFI" = "AssetFlags"
"DependencyFlagsFFI" = "DependencyFlags"
"ExportsConditionsFFI" = "ExportsConditions"
"EnvironmentFlagsFFI" = "EnvironmentFlags"
"BundleFlagsFFI" = "BundleFlags"
