[package]
authors = ["Devon Govett <devongovett@gmail.com>"]
name = "parcel-plugin-js"
version = "0.1.0"
edition = "2024"

[dependencies]
parcel-core = { path = "../core" }
rquickjs = { version = "0.11.0", features = ["full", "rust-alloc"] }
rquickjs-serde = "0.4.0"
rquickjs-extra-console = "0.2.1"
rquickjs-sys = "0.11.0"
serde_json = { version = "1.0.91", features = ["preserve_order"] }
serde = { version = "1.0.228", features = ["derive", "rc"] }
parcel-resolver = { path = "../parcel-resolver" }
parcel-macros = { path = "../macros" }
parcel_sourcemap = { version = "*", features = ["json"] }
indexmap = { version = "2.11.0", features = ["serde"] }
data-encoding = "2.3.2"
url = "*"
swc = "64"
swc_core = "66"
rust-embed = "8.11.0"
