use std::sync::Arc;

use indexmap::IndexMap;
use parcel_core::*;
use parcel_css::resolve_css_module_export;

use super::{RUNTIME_REQUIRE, Resolution, rsc::RscModule, runtime_name};

/// A module generated by the packager rather than originating from a source asset.
#[derive(Clone, Debug, PartialEq, Eq, Hash)]
pub enum SyntheticAsset {
  /// Exposes the requested CSS module exports of a non-JS asset as a JS module.
  CssModuleExports(u32),
  /// A shim module for a dependency that resolved to another bundle.
  Bundle { bundle: u32, kind: BundleShim },
  /// A generated React Server Components module.
  Rsc(RscModule),
}

#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash)]
pub enum BundleShim {
  /// Loads the bundle and its referenced bundles on demand, resolving to the
  /// exports of its main entry asset.
  Async,
  /// Wraps the `Async` shim with ESM interop for dynamic imports from ESM.
  AsyncInterop,
  /// Resolves to the URL of the bundle.
  Url,
  /// Resolves to the inlined content of the bundle.
  Inline,
}

impl BundleShim {
  fn id(&self, bundle: u32) -> String {
    match self {
      BundleShim::Async | BundleShim::Url | BundleShim::Inline => format!("b{}", bundle),
      BundleShim::AsyncInterop => format!("b{}i", bundle),
    }
  }
}

impl SyntheticAsset {
  pub fn id(&self, bundle_graph: &BundleGraph, project_root: &PathId) -> String {
    match self {
      SyntheticAsset::CssModuleExports(asset_index) => bundle_graph.asset_graph.assets
        [*asset_index as usize]
        .expect_asset()
        .id(project_root),
      SyntheticAsset::Bundle { bundle, kind } => kind.id(*bundle),
      SyntheticAsset::Rsc(module) => module.id(),
    }
  }

  pub fn dependencies<'a>(
    &self,
    bundle_graph: &'a BundleGraph,
    project_root: &PathId,
  ) -> IndexMap<String, Resolution<'a>> {
    let mut dependencies = IndexMap::new();
    match self {
      SyntheticAsset::Bundle {
        bundle,
        kind: BundleShim::Async,
      } => {
        let resolved_bundle = &bundle_graph.bundles[*bundle as usize];
        if let Some(main_entry_asset) = resolved_bundle.main_entry_asset {
          let asset = bundle_graph.asset_graph.assets[main_entry_asset].expect_asset();
          dependencies.insert("bundle".into(), Resolution::Asset(asset.id(project_root)));
        }
      }
      SyntheticAsset::Bundle {
        bundle,
        kind: BundleShim::AsyncInterop,
      } => {
        dependencies.insert(
          "bundle".into(),
          Resolution::Asset(BundleShim::Async.id(*bundle)),
        );
      }
      _ => {}
    }

    dependencies
  }

  pub fn write_content<W: std::fmt::Write>(
    &self,
    dest: &mut W,
    should_optimize: bool,
    bundle_graph: &BundleGraph,
    bundle: &Bundle,
    get_inline_bundle_content: &dyn Fn(usize) -> Result<Arc<dyn Content>, DiagnosticList>,
    project_root: &PathId,
  ) -> Result<(), DiagnosticList> {
    match self {
      SyntheticAsset::CssModuleExports(asset_index) => {
        if let AssetNode::Asset(asset) = &bundle_graph.asset_graph.assets[*asset_index as usize] {
          for exp in &asset.symbols.exports {
            if !exp.requested {
              continue;
            }

            if let Some(value) = resolve_css_module_export(
              &bundle_graph.asset_graph.assets,
              *asset_index as usize,
              exp.exported.as_str(),
            ) {
              write!(dest, "exports[{:?}]='{}';\n", exp.exported.as_str(), value)?;
            }
          }
        }
      }
      SyntheticAsset::Bundle {
        bundle: bundle_index,
        kind,
      } => match kind {
        BundleShim::Async => {
          let resolved_bundle = &bundle_graph.bundles[*bundle_index as usize];
          load_bundles(
            bundle_graph,
            bundle,
            resolved_bundle,
            dest,
            project_root,
            runtime_name(should_optimize, "require", RUNTIME_REQUIRE),
          )?;
        }
        BundleShim::AsyncInterop => {
          write!(
            dest,
            "module.exports={}(\"b{}\").then(m=>m&&m.__esModule?m:{{default:m}})",
            runtime_name(should_optimize, "require", RUNTIME_REQUIRE),
            bundle_index,
          )?;
        }
        BundleShim::Url => {
          let resolved_bundle = &bundle_graph.bundles[*bundle_index as usize];
          write!(
            dest,
            "module.exports=''+new URL({:?},import.meta.url)",
            resolved_bundle.relative_url(bundle).unwrap()
          )?;
        }
        BundleShim::Inline => {
          let content = get_inline_bundle_content(*bundle_index as usize)?.read()?;
          write!(
            dest,
            "module.exports={:?}",
            String::from_utf8_lossy(&content)
          )?;
        }
      },
      SyntheticAsset::Rsc(module) => {
        module.write(dest, should_optimize, bundle_graph, bundle, project_root)?;
      }
    }

    Ok(())
  }
}

pub(super) fn js_bundle_load_expression(
  bundle: &Bundle,
  from: &Bundle,
  require_name: &str,
) -> String {
  if bundle.target.output_format == OutputFormat::Commonjs {
    format!(
      "Promise.resolve({}({}))",
      require_name,
      serde_json::to_string(&bundle.relative_specifier(from).unwrap()).unwrap()
    )
  } else {
    // parcelLoadJS resolves dist-root-relative names against the runtime's distDir prefix.
    format!(
      "module.bundle.loadJS({})",
      serde_json::to_string(&bundle.name()).unwrap()
    )
  }
}

fn load_bundles<W: std::fmt::Write>(
  bundle_graph: &BundleGraph,
  from: &Bundle,
  bundle: &Bundle,
  res: &mut W,
  project_root: &PathId,
  require_name: &str,
) -> core::fmt::Result {
  let main_entry_id = bundle.main_entry_asset.unwrap();
  let asset = &bundle_graph.asset_graph.assets[main_entry_id].expect_asset();

  if !bundle.referenced_bundles.is_empty() {
    write!(res, "module.exports=Promise.all([")?;
    // TODO: recursive
    for referenced_index in &bundle.referenced_bundles {
      load_bundle(
        &bundle_graph.bundles[*referenced_index],
        from,
        res,
        require_name,
      )?;
      write!(res, ", ")?;
    }

    load_bundle(bundle, from, res, require_name)?;
    write!(
      res,
      "]).then(()=>{}('{}'));",
      require_name,
      asset.id(project_root)
    )?;
  } else {
    write!(res, "module.exports=")?;
    load_bundle(bundle, from, res, require_name)?;
    write!(
      res,
      ".then(()=>{}('{}'));",
      require_name,
      asset.id(project_root)
    )?;
  }

  Ok(())
}

fn load_bundle<W: std::fmt::Write>(
  bundle: &Bundle,
  from: &Bundle,
  res: &mut W,
  require_name: &str,
) -> core::fmt::Result {
  match &bundle.ty {
    AssetType::Js => {
      write!(
        res,
        "{}",
        js_bundle_load_expression(bundle, from, require_name)
      )
    }
    AssetType::Css => {
      write!(
        res,
        "module.bundle.loadCSS('./{}')",
        bundle.relative_url(from).unwrap()
      )
    }
    _ => Ok(()),
  }
}
