use std::sync::Arc;

use indexmap::IndexMap;
use parcel_core::*;
use parcel_css::resolve_css_module_export;

use super::{RUNTIME_REQUIRE, Resolution, rsc::RscModule, runtime_name};

/// A module generated by the packager rather than originating from a source asset.
#[derive(Clone, Debug, PartialEq, Eq, Hash)]
pub enum SyntheticAsset {
  /// Exposes the requested CSS module exports of a non-JS asset as a JS module.
  CssModuleExports(AssetIndex),
  /// A shim module for a dependency that resolved to another bundle.
  Bundle { bundle: u32, kind: BundleShim },
  /// An internalized async asset.
  Internalized(AssetIndex),
  /// Preserves the namespace wrapper used for dynamic imports from ESM.
  InternalizedInterop(AssetIndex),
  /// A generated React Server Components module.
  Rsc(RscModule),
}

#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash)]
pub enum BundleShim {
  /// Loads the bundle and its referenced bundles on demand, resolving to the
  /// exports of its main entry asset.
  Async(AssetIndex),
  /// Wraps the `Async` shim with ESM interop for dynamic imports from ESM.
  AsyncInterop(AssetIndex),
  /// Resolves to the URL of the bundle.
  Url,
  /// Resolves to the inlined content of the bundle.
  Inline(InlineType),
  /// Loads the bundle synchronously.
  Sync,
}

/// The value an inlined bundle's content is exposed as, from the dependency's ImportType.
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash)]
pub enum InlineType {
  /// A string of the bundle's content.
  Text,
  /// A Uint8Array of the bundle's content.
  Bytes,
  /// A CSSStyleSheet constructed from the bundle's content.
  StyleSheet,
}

impl From<ImportType> for InlineType {
  fn from(import_type: ImportType) -> Self {
    match import_type {
      ImportType::Bytes => InlineType::Bytes,
      ImportType::StyleSheet => InlineType::StyleSheet,
      _ => InlineType::Text,
    }
  }
}

impl BundleShim {
  pub(super) fn id(&self, bundle: u32, graph: &BundleGraph) -> String {
    // Neither physical bundle indices nor dense asset indices survive a merge
    // or an incremental rebuild. Cached module registries require stable IDs.
    let bundle = graph.bundles[bundle as usize].id;
    let asset_id = |a| graph.asset_graph.asset(a).id(&graph.project_root);
    match self {
      BundleShim::Url | BundleShim::Inline(InlineType::Text) | BundleShim::Sync => {
        format!("b{bundle:x}")
      }
      BundleShim::Async(a) => format!("a{bundle:x}_{}", asset_id(*a)),
      BundleShim::AsyncInterop(a) => format!("a{bundle:x}_{}i", asset_id(*a)),
      BundleShim::Inline(InlineType::Bytes) => format!("b{bundle:x}_bytes"),
      BundleShim::Inline(InlineType::StyleSheet) => format!("b{bundle:x}_css"),
    }
  }
}

impl SyntheticAsset {
  pub fn id(&self, bundle_graph: &BundleGraph, project_root: &PathId) -> String {
    match self {
      SyntheticAsset::CssModuleExports(asset_index) => bundle_graph
        .asset_graph
        .asset(*asset_index)
        .id(project_root),
      SyntheticAsset::Bundle { bundle, kind } => kind.id(*bundle, bundle_graph),
      SyntheticAsset::Internalized(asset_index) => format!(
        "i_{}",
        bundle_graph
          .asset_graph
          .asset(*asset_index)
          .id(project_root)
      ),
      SyntheticAsset::InternalizedInterop(asset_index) => format!(
        "{}_esm",
        SyntheticAsset::Internalized(*asset_index).id(bundle_graph, project_root)
      ),
      SyntheticAsset::Rsc(module) => module.id(),
    }
  }

  pub fn dependencies<'a>(
    &self,
    bundle_graph: &'a BundleGraph,
    project_root: &PathId,
  ) -> IndexMap<String, Resolution<'a>> {
    let mut dependencies = IndexMap::new();
    match self {
      SyntheticAsset::Bundle {
        kind: BundleShim::Async(entry_asset),
        ..
      } => {
        let asset = &bundle_graph.asset_graph.asset(*entry_asset);
        dependencies.insert("bundle".into(), Resolution::Asset(asset.id(project_root)));
      }
      SyntheticAsset::Bundle {
        bundle,
        kind: BundleShim::AsyncInterop(asset),
      } => {
        dependencies.insert(
          "bundle".into(),
          Resolution::Asset(BundleShim::Async(*asset).id(*bundle, bundle_graph)),
        );
      }
      _ => {}
    }

    dependencies
  }

  pub fn write_content<W: std::fmt::Write>(
    &self,
    dest: &mut W,
    should_optimize: bool,
    bundle_graph: &BundleGraph,
    bundle: &Bundle,
    get_inline_bundle_content: &dyn Fn(usize) -> Result<Arc<dyn Content>, DiagnosticList>,
    project_root: &PathId,
  ) -> Result<(), DiagnosticList> {
    match self {
      SyntheticAsset::CssModuleExports(asset_index) => {
        let asset = &bundle_graph.asset_graph.asset(*asset_index);
        for exp in &asset.symbols.exports {
          if !exp.requested {
            continue;
          }

          if let Some(value) = resolve_css_module_export(
            &bundle_graph.asset_graph,
            *asset_index,
            exp.exported.as_str(),
          ) {
            write!(dest, "exports[{:?}]='{}';\n", exp.exported.as_str(), value)?;
          }
        }
      }
      SyntheticAsset::Bundle {
        bundle: bundle_index,
        kind,
      } => match kind {
        BundleShim::Async(main_entry_id) => {
          load_bundles(
            bundle_graph,
            bundle,
            *bundle_index as usize,
            *main_entry_id,
            dest,
            project_root,
            runtime_name(should_optimize, "require", RUNTIME_REQUIRE),
          )?;
        }
        BundleShim::AsyncInterop(asset) => {
          write!(
            dest,
            "module.exports={}({:?}).then(m=>m&&m.__esModule?m:{{default:m}})",
            runtime_name(should_optimize, "require", RUNTIME_REQUIRE),
            BundleShim::Async(*asset).id(*bundle_index, bundle_graph)
          )?;
        }
        BundleShim::Url => {
          let resolved_bundle = &bundle_graph.bundles[*bundle_index as usize];
          write!(
            dest,
            "module.exports=module.bundle.resolve({:?})",
            resolved_bundle.stable_key()
          )?;
        }
        BundleShim::Inline(inline_type) => {
          let content = get_inline_bundle_content(*bundle_index as usize)?;
          match inline_type {
            InlineType::Text => {
              write!(dest, "module.exports={:?}", content.read_string()?)?;
            }
            InlineType::Bytes => {
              write!(dest, "module.exports=new Uint8Array([")?;
              for (i, byte) in content.read()?.iter().enumerate() {
                if i > 0 {
                  dest.write_char(',')?;
                }
                write!(dest, "{}", byte)?;
              }
              write!(dest, "])")?;
            }
            InlineType::StyleSheet => {
              write!(
                dest,
                "var s=new CSSStyleSheet();s.replaceSync({:?});module.exports=s",
                content.read_string()?
              )?;
            }
          }
        }
        BundleShim::Sync => {
          let resolved_bundle = &bundle_graph.bundles[*bundle_index as usize];
          let specifier = resolved_bundle.relative_specifier(bundle).unwrap();
          write!(
            dest,
            "module.exports=module.bundle.nodeRequire({:?})",
            specifier
          )?;
        }
      },
      SyntheticAsset::Internalized(asset_index) => {
        let asset = bundle_graph.asset_graph.asset(*asset_index);
        let id = asset.id(project_root);
        write!(
          dest,
          "module.exports=Promise.resolve().then(()=>{}({:?}))",
          runtime_name(should_optimize, "require", RUNTIME_REQUIRE),
          id
        )?;
      }
      SyntheticAsset::InternalizedInterop(asset_index) => {
        write!(
          dest,
          "module.exports={}({:?}).then(m=>m&&m.__esModule?m:{{default:m}})",
          runtime_name(should_optimize, "require", RUNTIME_REQUIRE),
          SyntheticAsset::Internalized(*asset_index).id(bundle_graph, project_root)
        )?;
      }
      SyntheticAsset::Rsc(module) => {
        module.write(dest, should_optimize, bundle_graph, bundle, project_root)?;
      }
    }

    Ok(())
  }
}

pub(super) fn js_bundle_load_expression(
  bundle: &Bundle,
  from: &Bundle,
  require_name: &str,
) -> String {
  if bundle.target.output_format == OutputFormat::Commonjs {
    format!(
      "Promise.resolve({}({}))",
      require_name,
      serde_json::to_string(&bundle.relative_specifier(from).unwrap()).unwrap()
    )
  } else {
    // parcelLoadJS resolves dist-root-relative names against the runtime's distDir prefix.
    format!(
      "module.bundle.loadJS({})",
      serde_json::to_string(&bundle.stable_key()).unwrap()
    )
  }
}

fn load_bundles<W: std::fmt::Write>(
  bundle_graph: &BundleGraph,
  from: &Bundle,
  bundle_index: usize,
  main_entry_id: AssetIndex,
  res: &mut W,
  project_root: &PathId,
  require_name: &str,
) -> core::fmt::Result {
  let asset = &bundle_graph.asset_graph.asset(main_entry_id);
  let bundle = &bundle_graph.bundles[bundle_index];

  // Load everything the bundle depends on, transitively, rather than relying on each bundle to
  // import its own siblings. Only JS and CSS bundles have loaders.
  let dependencies: Vec<usize> = bundle_graph
    .referenced_bundles(bundle_index)
    .skip(1)
    .filter(|&index| {
      matches!(
        bundle_graph.bundles[index].ty,
        AssetType::Js | AssetType::Css
      )
    })
    .collect();

  if !dependencies.is_empty() {
    write!(res, "module.exports=Promise.all([")?;
    for referenced_index in dependencies {
      load_bundle(
        bundle_graph,
        &bundle_graph.bundles[referenced_index],
        from,
        res,
        require_name,
      )?;
      write!(res, ", ")?;
    }

    load_bundle(bundle_graph, bundle, from, res, require_name)?;
    write!(
      res,
      "]).then(()=>{}('{}'));",
      require_name,
      asset.id(project_root)
    )?;
  } else {
    write!(res, "module.exports=")?;
    load_bundle(bundle_graph, bundle, from, res, require_name)?;
    write!(
      res,
      ".then(()=>{}('{}'));",
      require_name,
      asset.id(project_root)
    )?;
  }

  Ok(())
}

fn load_bundle<W: std::fmt::Write>(
  bundle_graph: &BundleGraph,
  bundle: &Bundle,
  from: &Bundle,
  res: &mut W,
  require_name: &str,
) -> core::fmt::Result {
  match &bundle.ty {
    AssetType::Js => {
      write!(
        res,
        "{}",
        js_bundle_load_expression(bundle, from, require_name)
      )
    }
    AssetType::Css => {
      // A common media gate lets the runtime mark the injected link so the
      // browser can deprioritize the fetch; the styles are correct without it.
      if let Some(media) = bundle_graph.common_style_media(bundle) {
        write!(
          res,
          "module.bundle.loadCSS({},{})",
          serde_json::to_string(&bundle.stable_key()).unwrap(),
          serde_json::to_string(&media).unwrap()
        )
      } else {
        write!(
          res,
          "module.bundle.loadCSS({})",
          serde_json::to_string(&bundle.stable_key()).unwrap()
        )
      }
    }
    _ => Ok(()),
  }
}
