[target.'cfg(target_env = "gnu")']
rustflags = [
  "-C", "link-arg=-Wl,-z,nodelete",
  "-C", "link-arg=-Wl,--export-dynamic",
]

[target.wasm32-unknown-unknown]
rustflags = ["-C", "link-arg=--export-table"]

[target.aarch64-apple-darwin]
rustflags = ["-C", "link-arg=-Wl,-export_dynamic"]
