export const LICENSE_STATE_ACTIVE = 'ACTIVE';
export const LICENSE_STATE_SUSPENDED = 'SUSPENDED';
export const LICENSE_STATE_EXPIRED = 'EXPIRED';
export const LICENSE_STATE_UNLICENSED = 'UNLICENSED';
