[package]
authors = ["Devon Govett <devongovett@gmail.com>"]
name = "parcel-core"
version = "0.1.0"
edition = "2024"

[dependencies]
bitflags = { version = "2.7.0", features = ["serde"] }
browserslist-rs = "0.20.0"
json-sourcemap = "0.2.0"
node-semver = "2.2.0"
serde = { version = "1.0.228", features = ["derive", "rc"] }
serde_bytes = "0.11.5"
serde-value = "0.7.0"
indexmap = { version = "2.11.0", features = ["serde"] }
glob-match = "*"
fixedbitset = "0.5.7"
url = "*"
percent-encoding = "2.2.0"
xxhash-rust = { version = "0.8.2", features = ["xxh3"] }
rustc-hash = "2.1.3"
parcel_sourcemap = "*"
serde_json = { version = "1.0.149", features = ["preserve_order"] }
hstr = { version = "4.0.1", features = ["serde"] }
either = "1.15.0"
anstyle = "*"
dotenvy = "0.15.7"
rayon = "1.7.0"
papaya = "0.2.4"
boxcar = "0.2.14"
smallvec = "1.13.2"
crossbeam-channel = "0.5.6"
parcel-highlight = { path = "../highlight" }
sha2-const-stable = "0.1.0"

[dev-dependencies]
pretty_assertions = "1.4.1"
