/**
 * Flowtype definitions for clean
 * Generated by Flowgen from a Typescript Definition
 * Flowgen v1.14.1
 */

import semver from "../index";

/**
 * Returns cleaned (removed leading/trailing whitespace, remove '=v' prefix) and parsed version, or null if version is invalid.
 */
declare function clean(
  version: string,
  optionsOrLoose?: boolean | semver.Options
): string | null;
declare module.exports: typeof clean;
