/**
 * Flowtype definitions for coerce
 * Generated by Flowgen from a Typescript Definition
 * Flowgen v1.14.1
 */

import semver from "../index";
import SemVer from "../classes/semver";

/**
 * Coerces a string to SemVer if possible
 */
declare function coerce(
  version: string | number | SemVer | null | void,
  options?: semver.CoerceOptions
): SemVer | null;
declare module.exports: typeof coerce;
