/**
 * Flowtype definitions for compare-loose
 * Generated by Flowgen from a Typescript Definition
 * Flowgen v1.14.1
 */

import SemVer from "../classes/semver";
declare function compareLoose(
  v1: string | SemVer,
  v2: string | SemVer
): 1 | 0 | -1;
declare module.exports: typeof compareLoose;
