/**
 * Flowtype definitions for eq
 * Generated by Flowgen from a Typescript Definition
 * Flowgen v1.14.1
 */

import SemVer from "../classes/semver";
import semver from "../index";

/**
 * v1 == v2 This is true if they're logically equivalent, even if they're not the exact same string. You already know how to compare strings.
 */
declare function eq(
  v1: string | SemVer,
  v2: string | SemVer,
  optionsOrLoose?: boolean | semver.Options
): boolean;
declare module.exports: typeof eq;
