/**
 * Flowtype definitions for lte
 * Generated by Flowgen from a Typescript Definition
 * Flowgen v1.14.1
 */

import SemVer from "../classes/semver";
import semver from "../index";

/**
 * v1 <= v2
 */
declare function lte(
  v1: string | SemVer,
  v2: string | SemVer,
  optionsOrLoose?: boolean | semver.Options
): boolean;
declare module.exports: typeof lte;
