/**
 * Flowtype definitions for major
 * Generated by Flowgen from a Typescript Definition
 * Flowgen v1.14.1
 */

import SemVer from "../classes/semver";
import semver from "../index";

/**
 * Return the major version number.
 */
declare function major(
  version: string | SemVer,
  optionsOrLoose?: boolean | semver.Options
): number;
declare module.exports: typeof major;
