/**
 * Flowtype definitions for minor
 * Generated by Flowgen from a Typescript Definition
 * Flowgen v1.14.1
 */

import SemVer from "../classes/semver";
import semver from "../index";

/**
 * Return the minor version number.
 */
declare function minor(
  version: string | SemVer,
  optionsOrLoose?: boolean | semver.Options
): number;
declare module.exports: typeof minor;
