/**
 * Flowtype definitions for parse
 * Generated by Flowgen from a Typescript Definition
 * Flowgen v1.14.1
 */

import SemVer from "../classes/semver";
import semver from "../index";

/**
 * Return the parsed version as a SemVer object, or null if it's not valid.
 */
declare function parse(
  version: string | SemVer | null | void,
  optionsOrLoose?: boolean | semver.Options
): SemVer | null;
declare module.exports: typeof parse;
