/**
 * Flowtype definitions for patch
 * Generated by Flowgen from a Typescript Definition
 * Flowgen v1.14.1
 */

import SemVer from "../classes/semver";
import semver from "../index";

/**
 * Return the patch version number.
 */
declare function patch(
  version: string | SemVer,
  optionsOrLoose?: boolean | semver.Options
): number;
declare module.exports: typeof patch;
