/**
 * Flowtype definitions for prerelease
 * Generated by Flowgen from a Typescript Definition
 * Flowgen v1.14.1
 */

import SemVer from "../classes/semver";
import semver from "../index";

/**
 * Returns an array of prerelease components, or null if none exist.
 */
declare function prerelease(
  version: string | SemVer,
  optionsOrLoose?: boolean | semver.Options
): $ReadOnlyArray<string | number> | null;
declare module.exports: typeof prerelease;
