/**
 * Flowtype definitions for rcompare
 * Generated by Flowgen from a Typescript Definition
 * Flowgen v1.14.1
 */

import SemVer from "../classes/semver";
import semver from "../index";

/**
 * The reverse of compare.
 *
 * Sorts in descending order when passed to `Array.sort()`.
 */
declare function rcompare(
  v1: string | SemVer,
  v2: string | SemVer,
  optionsOrLoose?: boolean | semver.Options
): 1 | 0 | -1;
declare module.exports: typeof rcompare;
