/**
 * Flowtype definitions for satisfies
 * Generated by Flowgen from a Typescript Definition
 * Flowgen v1.14.1
 */

import Range from "../classes/range";
import SemVer from "../classes/semver";
import semver from "../index";

/**
 * Return true if the version satisfies the range.
 */
declare function satisfies(
  version: string | SemVer,
  range: string | Range,
  optionsOrLoose?: boolean | semver.Options
): boolean;
declare module.exports: typeof satisfies;
