/**
 * Flowtype definitions for valid
 * Generated by Flowgen from a Typescript Definition
 * Flowgen v1.14.1
 */

import semver from "../index";
import SemVer from "../classes/semver";

/**
 * Return the parsed version as a string, or null if it's not valid.
 */
declare function valid(
  version: string | SemVer | null | void,
  optionsOrLoose?: boolean | semver.Options
): string | null;
declare module.exports: typeof valid;
