[package]
authors = ["Devon Govett <devongovett@gmail.com>"]
name = "parcel"
version = "0.1.0"
edition = "2024"

[dependencies]
parcel-core = { path = "../core" }
parcel-plugin-abi = { path = "../parcel-plugin-abi" }
parcel-js = { path = "../js" }
parcel-resolver = { path = "../parcel-resolver" }
indexmap = { version = "2.11.0", features = ["serde"] }
parcel-css = { path = "../css" }
parcel-html = { path = "../html" }
xxhash-rust = { version = "0.8.2", features = ["xxh3"] }
parcel-image = { path = "../image" }
serde_json = { version = "1.0.91", features = ["preserve_order"] }
serde = { version = "1.0.228", features = ["derive", "rc"] }
parcel-watcher = { git = "https://github.com/parcel-bundler/watcher.git", branch = "rust" }
parcel-plugin-js = { path = "../plugin-js" }
parcel-tailwind = { path = "../tailwind" }
tiny_http = "0.12.0"
tungstenite = "0.28.0"
url = "*"
toml = "1.1.2"
serde_yaml_ng = "0.10"
base64-url = "3.0.2"
data-encoding = "2.3.2"
pathdiff = "0.2.0"
glob-match = "*"
mimalloc = "*"
fixedbitset = "0.5.7"
percent-encoding = "2.2.0"

[dev-dependencies]
parcel_sourcemap = { version = "*", features = ["json"] }
rquickjs = { version = "0.11.0", features = ["full"] }
rquickjs-serde = "0.4.0"
testing_macros = "1.0.1"
pretty_assertions = "1.4.1"
criterion = { version = "*", features = ["html_reports"] }

[[bench]]
name = "benchmark"
harness = false
