[package]
authors = ["Devon Govett <devongovett@gmail.com>"]
name = "parcel"
version = "0.1.0"
edition = "2024"

[dependencies]
parcel-core = { path = "../core" }
parcel-js-swc-core = { path = "../../packages/transformers/js/core" }
parcel-resolver = { path = "../parcel-resolver" }
indexmap = { version = "=2.11.0", features = ["serde"] }
node-semver = "2.2.0"
parcel-html = { path = "../html" }
lightningcss = { version = "1.0.0-alpha.63", features = ["into_owned", "visitor"] }
xxhash-rust = { version = "0.8.2", features = ["xxh3"] }
parcel-image = { path = "../image" }
serde_json = { version = "1.0.91", features = ["preserve_order"] }
serde = { version = "1.0.123", features = ["derive", "rc"] }
parcel-watcher = { path = "/Users/devongovett/dev/watcher/rust" }
parcel-plugin-js = { path = "../plugin-js" }
tiny_http = "0.12.0"
# tungstenite = "0.28.0"
url = "*"
