[package]
authors = ["Devon Govett <devongovett@gmail.com>"]
name = "parcel"
version = "0.1.0"
edition = "2024"

[dependencies]
parcel-core = { path = "../core" }
parcel-js = { path = "../js" }
parcel-resolver = { path = "../parcel-resolver" }
indexmap = { version = "=2.11.0", features = ["serde"] }
parcel-css = { path = "../css" }
parcel-html = { path = "../html" }
xxhash-rust = { version = "0.8.2", features = ["xxh3"] }
parcel-image = { path = "../image" }
serde_json = { version = "1.0.91", features = ["preserve_order"] }
serde = { version = "1.0.123", features = ["derive", "rc"] }
parcel-watcher = { git = "https://github.com/parcel-bundler/watcher.git", branch = "rust" }
parcel-plugin-js = { path = "../plugin-js" }
tiny_http = "0.12.0"
tungstenite = "0.28.0"
url = "*"
