/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export function findAncestorFile(
  filenames: Array<string>,
  from: string,
  root: string,
): string | null;
export function findFirstFile(names: Array<string>): string | null;
export function findNodeModule(module: string, from: string): string | null;
