/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export function hashString(s: string): string;
export function hashBuffer(buf: Buffer): string;
export class Hash {
  constructor();
  writeString(s: string): void;
  writeBuffer(buf: Buffer): void;
  finish(): string;
}
