/**
 * Flowtype definitions for gtr
 * Generated by Flowgen from a Typescript Definition
 * Flowgen v1.14.1
 */

import Range from "../classes/range";
import SemVer from "../classes/semver";
import semver from "../index";

/**
 * Return true if version is greater than all the versions possible in the range.
 */
declare function gtr(
  version: string | SemVer,
  range: string | Range,
  optionsOrLoose?: boolean | semver.Options
): boolean;
declare module.exports: typeof gtr;
