/**
 * Flowtype definitions for intersects
 * Generated by Flowgen from a Typescript Definition
 * Flowgen v1.14.1
 */

import Range from "../classes/range";
import semver from "../index";

/**
 * Return true if any of the ranges comparators intersect
 */
declare function intersects(
  range1: string | Range,
  range2: string | Range,
  optionsOrLoose?: boolean | semver.Options
): boolean;
declare module.exports: typeof intersects;
