/**
 * Flowtype definitions for min-version
 * Generated by Flowgen from a Typescript Definition
 * Flowgen v1.14.1
 */

import Range from "../classes/range";
import SemVer from "../classes/semver";
import semver from "../index";

/**
 * Return the lowest version that can possibly match the given range.
 */
declare function minVersion(
  range: string | Range,
  optionsOrLoose?: boolean | semver.Options
): SemVer | null;
declare module.exports: typeof minVersion;
