/**
 * Flowtype definitions for subset
 * Generated by Flowgen from a Typescript Definition
 * Flowgen v1.14.1
 */

import Range from "../classes/range";
import semver from "../index";

/**
 * Return true if the subRange range is entirely contained by the superRange range.
 */
declare function subset(
  sub: string | Range,
  dom: string | Range,
  options?: semver.Options
): boolean;
declare module.exports: typeof subset;
