/**
 * Flowtype definitions for valid
 * Generated by Flowgen from a Typescript Definition
 * Flowgen v1.14.1
 */

import Range from "../classes/range";
import semver from "../index";

/**
 * Return the valid range or null if it's not valid
 */
declare function validRange(
  range: string | Range | null | void,
  optionsOrLoose?: boolean | semver.Options
): string;
declare module.exports: typeof validRange;
