// Generated by CoffeeScript 1.12.6
(function() {
  module.exports = (function(_this) {
    return function(a, b) {
      return a + b;
    };
  })(this);

}).call(this);

//# sourceMappingURL=sum.map
