[package]
authors = ["Devon Govett <devongovett@gmail.com>"]
name = "parcel-image"
version = "0.1.0"
edition = "2024"

[dependencies]
parcel-core = { path = "../core" }
image = { version = "0.25.9", default-features = false, features = [
  "avif",
  "bmp",
  "gif",
  "ico",
  "jpeg",
  "png",
  "rayon",
  "tiff",
  "webp",
] }
fast_image_resize = { version = "5.4.0", features = ["image"] }
webp = "0.3.1"
oxipng = { version = "9.1.2", default-features = false, features = [
  "parallel",
] }
mozjpeg-sys = "2.0.0"
mozjpeg = "0.10.13"
