use std::collections::VecDeque;

use fixedbitset::FixedBitSet;
use parcel_core::{AssetGraph, BundleBehavior, Priority};

use super::{bundle_roots::BundleRoots, reachability::Reachability};

#[derive(Clone, Copy, Debug)]
pub enum AvailabilityEdgeKind {
  // The target loads before its importer. Only the importer's IN is safe.
  Sync,
  // The target can use its parent's IN plus the parent's synchronous asset classes.
  Lazy,
  // Ordered, non-isolated parallel occurrences in the same loading context.
  Parallel,
}

#[derive(Clone, Copy, Debug)]
pub struct AvailabilityEdge {
  // Dense destination root index, not an AssetIndex or a reachability class ID.
  root: u32,
  // Selects which parent facts and preceding parallel occurrences reach this target.
  kind: AvailabilityEdgeKind,
}

impl AvailabilityEdge {
  pub fn new(root: u32, kind: AvailabilityEdgeKind) -> Self {
    Self { root, kind }
  }

  pub fn root(&self) -> usize {
    self.root as usize
  }

  pub fn kind(&self) -> AvailabilityEdgeKind {
    self.kind
  }
}

pub struct AvailabilityGraph {
  // Root index -> bitset of synchronously loaded class IDs (the transpose of
  // original reachability). Immutable throughout analysis and requirement filtering.
  synchronous: Vec<FixedBitSet>,
  // Root-indexed set whose IN stays empty: entries, inline/isolated roots,
  // environment boundaries, and roots without a live path from these boundaries.
  boundaries: FixedBitSet,
  // Each group is one asset's ordered boundary dependencies. Store it only once,
  // even when many roots reach that asset. Groups are indexed by source class.
  // Class c owns groups in [offsets[c], offsets[c + 1]). The last offset is a sentinel.
  class_group_offsets: Vec<u32>,
  // Group g owns edges[group_edge_offsets[g]..group_edge_offsets[g + 1]].
  // Keeping groups separate prevents prefixes leaking between source assets in one class.
  group_edge_offsets: Vec<u32>,
  // Flat ordered occurrence lists. A shared source's edges are stored once,
  // rather than expanded into a separate list for every root that reaches it.
  edges: Vec<AvailabilityEdge>,
}

pub struct AvailabilityState {
  // Reused root-major IN matrix. Rows are reset in place before each round.
  available: Vec<FixedBitSet>,
  // Reused worklist and membership set for the descending must analysis.
  queue: VecDeque<usize>,
  queued: FixedBitSet,
  // Scratch rows for the current IN, OUT, and ordered parallel prefix.
  input: FixedBitSet,
  output: FixedBitSet,
  parallel: FixedBitSet,
}

impl AvailabilityState {
  pub fn new(graph: &AvailabilityGraph) -> Self {
    let root_count = graph.root_count();
    let class_count = graph.class_count();
    Self {
      available: vec![FixedBitSet::with_capacity(class_count); root_count],
      queue: VecDeque::with_capacity(root_count),
      queued: FixedBitSet::with_capacity(root_count),
      input: FixedBitSet::with_capacity(class_count),
      output: FixedBitSet::with_capacity(class_count),
      parallel: FixedBitSet::with_capacity(class_count),
    }
  }

  pub fn solve<'a>(
    &'a mut self,
    graph: &AvailabilityGraph,
    roots: &BundleRoots,
  ) -> &'a [FixedBitSet] {
    self.solve_with(graph, |root| roots.is_active(root))
  }

  fn solve_with<'a>(
    &'a mut self,
    graph: &AvailabilityGraph,
    is_active: impl Fn(usize) -> bool,
  ) -> &'a [FixedBitSet] {
    self.queue.clear();
    self.queued.clear();

    // TOP is the universe of classes. Reinitialize the existing allocations;
    // inactive roots have no IN row and no outgoing loading occurrences.
    for root in 0..self.available.len() {
      self.available[root].clear();
      if is_active(root) {
        if !graph.is_boundary(root) {
          self.available[root].insert_range(..);
        }
        self.queue.push_back(root);
        self.queued.insert(root);
      }
    }

    while let Some(root) = self.queue.pop_front() {
      self.queued.set(root, false);
      // Snapshot once: self edges may shrink this root during the scan.
      self.input.clone_from(&self.available[root]);
      self.output.clone_from(&self.input);
      self.output.union_with(graph.synchronous_classes(root));

      for class in graph.synchronous_classes(root).ones() {
        for group in graph.groups_for_class(class) {
          self.parallel.clone_from(&self.output);
          for edge in graph.edges_for_group(group) {
            // An edge into a removed root no longer represents an independent
            // loading occurrence. Its source groups are already generated by
            // each surviving root that synchronously reaches their assets.
            let target = edge.root();
            if !is_active(target) {
              continue;
            }

            let contribution = match edge.kind() {
              AvailabilityEdgeKind::Sync => &self.input,
              AvailabilityEdgeKind::Lazy => &self.output,
              AvailabilityEdgeKind::Parallel => &self.parallel,
            };

            if !graph.is_boundary(target)
              && intersect_changed(&mut self.available[target], contribution)
              && !self.queued.put(target)
            {
              self.queue.push_back(target);
            }

            if matches!(edge.kind(), AvailabilityEdgeKind::Parallel) && !graph.is_boundary(target) {
              self.parallel.union_with(graph.synchronous_classes(target));
            }
          }
        }
      }
    }

    &self.available
  }

  #[cfg(test)]
  pub fn rows(&self) -> &[FixedBitSet] {
    &self.available
  }
}

impl AvailabilityGraph {
  pub fn from_asset_graph(
    asset_graph: &AssetGraph,
    roots: &BundleRoots,
    reachability: &Reachability,
  ) -> Self {
    let root_count = roots.len();

    // Roots whose availability must be reset regardless of their incoming dependencies.
    let mut boundaries = FixedBitSet::with_capacity(root_count);
    for (root, asset) in roots.iter_all() {
      if roots.is_entry(asset) || roots.bundle_behavior(asset) != BundleBehavior::None {
        boundaries.insert(root);
      }
    }

    // (Source class, ordered root dependencies) for each asset with boundary edges.
    let mut groups: Vec<(usize, Vec<AvailabilityEdge>)> = Vec::new();

    for (source, asset, _) in asset_graph.dfs() {
      if reachability.reachable_roots(source).is_clear() {
        continue;
      }

      // Retain dependency indices until sorting restores source order across symbol targets.
      let mut edges = Vec::new();

      for (dep_index, target) in asset_graph.resolved_dependencies_with_indices(asset) {
        // Only dependencies targeting explicit roots cross a dataflow boundary.
        let Some(root) = roots.root_index(target) else {
          continue;
        };

        let dep = &asset.dependencies[dep_index];
        let target_asset = asset_graph.asset(target);

        // Cross-environment dependencies start an independent availability scope.
        // Explicit inline/isolated roots were already marked as boundaries above.
        if asset.target.environment != target_asset.target.environment {
          boundaries.insert(root);
        }

        // Choose the transfer rule applied to each incoming occurrence of this root.
        let kind = match dep.priority {
          Priority::Lazy => AvailabilityEdgeKind::Lazy,
          // Non-isolated parallel roots contribute their synchronous classes to
          // subsequent parallel occurrences in this source asset's dependency list.
          Priority::Parallel if roots.bundle_behavior(target) == BundleBehavior::None => {
            AvailabilityEdgeKind::Parallel
          }
          _ => AvailabilityEdgeKind::Sync,
        };

        edges.push((dep_index, AvailabilityEdge::new(root as u32, kind)));
      }

      if !edges.is_empty() {
        // Resolved symbol targets can be emitted after a later dependency's
        // side-effect target. Prefixes must follow the original dependency order.
        edges.sort_by_key(|(dep_index, _)| *dep_index);
        groups.push((
          reachability.class(source),
          edges.into_iter().map(|(_, edge)| edge).collect(),
        ));
      }
    }

    Self::new(reachability, boundaries, groups)
  }

  pub fn new(
    reachability: &Reachability,
    mut boundaries: FixedBitSet,
    mut groups: Vec<(usize, Vec<AvailabilityEdge>)>,
  ) -> Self {
    // Root-major view of the same relation: each bit is a whole asset class,
    // whose members always enter and leave availability together.
    let root_count = boundaries.len();
    let mut synchronous = vec![FixedBitSet::with_capacity(reachability.class_count()); root_count];
    for (class, roots) in reachability.classes() {
      for root in roots.ones() {
        synchronous[root].insert(class);
      }
    }

    groups.sort_by_key(|(class, _)| *class);

    // First count groups per source class, then convert the counts to prefix offsets.
    let mut class_group_offsets = vec![0u32; reachability.class_count() + 1];
    // Append one end offset after flattening each source asset's occurrence list.
    let mut group_edge_offsets = vec![0u32];
    // Shared backing storage for every group's ordered root dependencies.
    let mut edges = Vec::new();

    for (class, group) in groups {
      class_group_offsets[class + 1] += 1;
      edges.extend(group);
      group_edge_offsets.push(edges.len() as u32);
    }

    for class in 0..reachability.class_count() {
      class_group_offsets[class + 1] += class_group_offsets[class];
    }

    // Dead/stale roots can be discovered by BundleRoots without having a live
    // loading path. Never let a disconnected cycle retain TOP and justify an
    // optimization. Reachability here ignores transfer facts and follows only
    // the implicit root graph, without expanding its root/edge cross product.

    // Roots found by a graph walk starting from the known reset boundaries.
    let mut reachable = boundaries.clone();
    // Newly reached roots whose synchronous classes may reveal more root dependencies.
    let mut queue: VecDeque<_> = reachable.ones().collect();
    let mut seen_classes = FixedBitSet::with_capacity(reachability.class_count());
    while let Some(root) = queue.pop_front() {
      for class in synchronous[root].ones() {
        if seen_classes.put(class) {
          continue;
        }

        // All groups owned by this class form one contiguous range of edge storage.
        let start = class_group_offsets[class] as usize;
        let end = class_group_offsets[class + 1] as usize;
        for edge in &edges[group_edge_offsets[start] as usize..group_edge_offsets[end] as usize] {
          if !reachable.put(edge.root()) {
            queue.push_back(edge.root());
          }
        }
      }
    }

    for root in 0..boundaries.len() {
      if !reachable.contains(root) {
        boundaries.insert(root);
      }
    }

    Self {
      synchronous,
      boundaries,
      class_group_offsets,
      group_edge_offsets,
      edges,
    }
  }

  #[cfg(test)]
  pub fn solve(&self) -> Vec<FixedBitSet> {
    let mut state = AvailabilityState::new(self);
    state.solve_with(self, |_| true).to_vec()
  }

  pub fn needed_roots(
    &self,
    mut reachability: Reachability,
    roots: &BundleRoots,
    available: &[FixedBitSet],
  ) -> Reachability {
    // Root index -> class containing the root asset; retain its explicit bundle identity.
    let root_classes: Vec<_> = roots
      .iter_all()
      .map(|(_, asset)| reachability.class(asset))
      .collect();

    // Project the immutable original classes through the final active-root set.
    // Classes that become equal may stay separate here: BundleKey equality still
    // deduplicates them during placement.
    reachability.retain_active_roots(roots);

    // Reuse reachability's storage for final requirements rather than keeping
    // another class-by-root matrix.
    for (root, _) in roots.iter_active() {
      let input = &available[root];
      for class in self.synchronous_classes(root).ones() {
        // Keep explicit bundle roots and their co-generated class. Eliminating
        // a root also requires internalizing its dependency resolutions.
        if class != root_classes[root] && input.contains(class) {
          reachability.remove_root_from_class(class, root);
        }
      }
    }

    reachability
  }

  pub fn synchronous_classes(&self, root: usize) -> &FixedBitSet {
    &self.synchronous[root]
  }

  #[cfg(test)]
  pub fn edge_count(&self) -> usize {
    self.edges.len()
  }

  pub fn root_count(&self) -> usize {
    self.synchronous.len()
  }

  pub fn class_count(&self) -> usize {
    self.class_group_offsets.len() - 1
  }

  fn is_boundary(&self, root: usize) -> bool {
    self.boundaries.contains(root)
  }

  fn groups_for_class(&self, class: usize) -> std::ops::Range<u32> {
    self.class_group_offsets[class]..self.class_group_offsets[class + 1]
  }

  fn edges_for_group(&self, group: u32) -> &[AvailabilityEdge] {
    &self.edges[self.group_edge_offsets[group as usize] as usize
      ..self.group_edge_offsets[group as usize + 1] as usize]
  }
}

fn intersect_changed(target: &mut FixedBitSet, source: &FixedBitSet) -> bool {
  debug_assert_eq!(target.len(), source.len());
  // Report whether any facts were removed, without cloning the original target set.
  let mut changed = false;
  for (target, source) in target.as_mut_slice().iter_mut().zip(source.as_slice()) {
    // Intersect one machine word and detect a change during the same scan.
    let next = *target & source;
    changed |= next != *target;
    *target = next;
  }
  changed
}
